import { PrismaClient } from '@prisma/client'

const db = new PrismaClient()

async function main() {
  console.log('🌱 Seeding GreenHaven Nursery database...\n')

  // Clean existing data
  await db.orderItem.deleteMany()
  await db.cartItem.deleteMany()
  await db.order.deleteMany()
  await db.plant.deleteMany()
  await db.category.deleteMany()

  // ─── CATEGORIES ───────────────────────────────────────────────────
  console.log('📦 Creating categories...')
  const categories = await Promise.all([
    db.category.create({
      data: {
        name: 'Flowering Plants',
        slug: 'flowering-plants',
        description: 'Vibrant blooms that add color and fragrance to your garden, balcony, or living space. From classic roses to exotic orchids.',
        icon: 'Flower2',
        order: 1,
      },
    }),
    db.category.create({
      data: {
        name: 'Indoor Plants',
        slug: 'indoor-plants',
        description: 'Beautiful houseplants that thrive indoors, purify the air, and bring nature into your home or office.',
        icon: 'Home',
        order: 2,
      },
    }),
    db.category.create({
      data: {
        name: 'Herbs & Spices',
        slug: 'herbs-spices',
        description: 'Fresh aromatic herbs and spice plants for your kitchen garden. Grow your own flavors right at home.',
        icon: 'Leaf',
        order: 3,
      },
    }),
    db.category.create({
      data: {
        name: 'Vegetables',
        slug: 'vegetables',
        description: 'Fresh vegetable seedlings and plants for your home garden. Grow organic produce for your family.',
        icon: 'Carrot',
        order: 4,
      },
    }),
    db.category.create({
      data: {
        name: 'Fruit Plants',
        slug: 'fruit-plants',
        description: 'Fruit-bearing trees and plants suitable for Nepali climate. Enjoy homegrown fruits year after year.',
        icon: 'Apple',
        order: 5,
      },
    }),
    db.category.create({
      data: {
        name: 'Succulents & Cacti',
        slug: 'succulents-cacti',
        description: 'Low-maintenance drought-tolerant plants perfect for busy plant parents and modern decor.',
        icon: 'Sun',
        order: 6,
      },
    }),
    db.category.create({
      data: {
        name: 'Trees & Shrubs',
        slug: 'trees-shrubs',
        description: 'Ornamental and functional trees and shrubs for landscaping, shade, and environmental benefits.',
        icon: 'TreePine',
        order: 7,
      },
    }),
    db.category.create({
      data: {
        name: 'Medicinal Plants',
        slug: 'medicinal-plants',
        description: 'Traditional Ayurvedic and medicinal plants with proven health benefits. Nepal\'s rich herbal heritage at your doorstep.',
        icon: 'Heart',
        order: 8,
      },
    }),
  ])

  const catMap = new Map(categories.map((c) => [c.slug, c.id]))
  console.log(`✅ Created ${categories.length} categories\n`)

  // ─── PLANTS ───────────────────────────────────────────────────────
  console.log('🌿 Creating plants...')

  const plantsData = [
    // ── FLOWERING PLANTS ──────────────────────────────────────────
    {
      name: 'Rose',
      slug: 'rose',
      scientificName: 'Rosa',
      description: 'The timeless rose is a garden favorite across Nepal, prized for its exquisite layered petals and captivating fragrance. Available in shades of red, pink, yellow, and white, roses thrive in Kathmandu Valley\'s temperate climate. With proper care, they bloom profusely from spring through autumn.',
      shortDesc: 'Classic garden beauty with fragrant blooms in vibrant colors.',
      price: 350,
      originalPrice: 450,
      imageUrl: 'https://picsum.photos/seed/rose-nepal/600/400',
      categoryId: catMap.get('flowering-plants')!,
      climate: 'Temperate',
      elevation: '500-2500m',
      season: 'Spring-Autumn',
      sunlight: 'Full Sun',
      waterNeed: 'Moderate',
      soilType: 'Loamy, well-draining with organic matter',
      soilPH: '6.0-6.5',
      temperature: '15-28°C',
      humidity: '50-70%',
      matureHeight: '60-150cm',
      spread: '45-90cm',
      bloomTime: 'March-November',
      difficulty: 'Moderate',
      nutrients: 'NPK 10-10-10, Rose-specific fertilizer, Bone Meal, Epsom Salt',
      fertilizer: 'Apply balanced NPK every 4-6 weeks during growing season; supplement with bone meal in spring.',
      pruning: 'Prune in late winter before new growth. Remove dead wood and shape the bush. Deadhead spent blooms to encourage reblooming.',
      propagation: 'Hardwood cuttings in winter, softwood cuttings in summer. Can also be propagated by layering.',
      companionPlants: 'Garlic, Marigold, Lavender, Sage',
      uses: 'Ornamental, Fragrance, Cut Flowers, Gifting, Essential Oils',
      medicinalUses: 'Rose water for skin, petals used in traditional remedies for digestion and sore throat',
      edible: false,
      indoor: false,
      outdoor: true,
      fragrance: true,
      airPurifying: false,
      petSafe: true,
      inStock: true,
      stockCount: 75,
      featured: true,
      rating: 4.8,
      reviewCount: 156,
      tags: 'rose, flowering, fragrant, garden, classic, popular',
    },
    {
      name: 'Jasmine',
      slug: 'jasmine',
      scientificName: 'Jasminum grandiflorum',
      description: 'Jasmine is beloved across Nepal for its intoxicating sweet fragrance that fills evening gardens. This evergreen vine produces clusters of delicate white flowers throughout the warm months. In Nepali culture, jasmine garlands are used in pujas and celebrations, making it a culturally significant plant.',
      shortDesc: 'Intoxicatingly fragrant white flowers perfect for gardens and puja.',
      price: 300,
      originalPrice: 380,
      imageUrl: 'https://picsum.photos/seed/jasmine-flower/600/400',
      categoryId: catMap.get('flowering-plants')!,
      climate: 'Subtropical',
      elevation: '100-1500m',
      season: 'Summer-Monsoon',
      sunlight: 'Full Sun to Partial Shade',
      waterNeed: 'Moderate',
      soilType: 'Loamy, well-draining, rich in organic matter',
      soilPH: '6.0-7.0',
      temperature: '18-35°C',
      humidity: '60-80%',
      matureHeight: '90-300cm',
      spread: '60-120cm',
      bloomTime: 'June-October',
      difficulty: 'Easy',
      nutrients: 'NPK 5-10-5, Phosphorus-rich fertilizer, Compost',
      fertilizer: 'Apply phosphorus-rich fertilizer in spring to promote flowering; compost monthly during growing season.',
      pruning: 'Prune after flowering to maintain shape. Pinch growing tips to encourage lateral branching and more flowers.',
      propagation: 'Semi-hardwood cuttings in monsoon season. Also propagated by layering and division.',
      companionPlants: 'Rose, Hibiscus, Bougainvillea',
      uses: 'Ornamental, Fragrance, Puja, Garland Making, Tea, Essential Oil',
      medicinalUses: 'Used in Ayurveda for anxiety relief, skin care, and as a mild sedative. Jasmine tea aids digestion.',
      edible: true,
      indoor: true,
      outdoor: true,
      fragrance: true,
      airPurifying: true,
      petSafe: true,
      inStock: true,
      stockCount: 60,
      featured: true,
      rating: 4.7,
      reviewCount: 132,
      tags: 'jasmine, fragrant, flowering, puja, vine, aromatic',
    },
    {
      name: 'Orchid',
      slug: 'orchid',
      scientificName: 'Dendrobium nobile',
      description: 'The Dendrobium orchid is Nepal\'s national flower, found naturally in the mid-hill forests. These stunning epiphytic orchids produce graceful sprays of flowers in purple, white, and pink hues. They symbolize beauty and resilience, thriving in Nepal\'s diverse climate zones with minimal care.',
      shortDesc: 'Nepal\'s national flower with stunning sprays of colorful blooms.',
      price: 1200,
      originalPrice: 1500,
      imageUrl: 'https://picsum.photos/seed/orchid-nepal/600/400',
      categoryId: catMap.get('flowering-plants')!,
      climate: 'Subtropical to Temperate',
      elevation: '500-2500m',
      season: 'Spring',
      sunlight: 'Bright Indirect Light',
      waterNeed: 'Moderate',
      soilType: 'Orchid bark mix, sphagnum moss, well-draining',
      soilPH: '5.5-6.5',
      temperature: '15-28°C',
      humidity: '60-80%',
      matureHeight: '30-60cm',
      spread: '20-40cm',
      bloomTime: 'February-May',
      difficulty: 'Moderate',
      nutrients: 'Orchid-specific fertilizer (30-10-10), Seaweed extract',
      fertilizer: 'Feed with diluted orchid fertilizer every 2 weeks during growing season. Reduce feeding in winter.',
      pruning: 'Remove spent flower spikes at the base. Do not cut healthy green canes as they store nutrients.',
      propagation: 'Division of pseudobulbs with 3-4 canes each. Also by keiki (baby plant) separation.',
      companionPlants: 'Ferns, Bromeliads, Philodendron',
      uses: 'Ornamental, National Symbol, Gift, Collection, Decoration',
      medicinalUses: 'In traditional medicine, used for fever, cough, and as a tonic. Dendrobium extract used in herbal supplements.',
      edible: false,
      indoor: true,
      outdoor: true,
      fragrance: true,
      airPurifying: true,
      petSafe: true,
      inStock: true,
      stockCount: 35,
      featured: true,
      rating: 4.9,
      reviewCount: 89,
      tags: 'orchid, national flower, dendrobium, exotic, premium, nepal',
    },
    {
      name: 'Hibiscus',
      slug: 'hibiscus',
      scientificName: 'Hibiscus rosa-sinensis',
      description: 'Hibiscus is a showstopper in any Nepali garden with its large, trumpet-shaped flowers in vivid reds, oranges, pinks, and yellows. This tropical shrub blooms almost year-round in warmer regions like Terai and Kathmandu Valley. The flowers are also used to make refreshing hibiscus tea and traditional hair care remedies.',
      shortDesc: 'Bold tropical blooms in striking colors that flower year-round.',
      price: 280,
      originalPrice: 350,
      imageUrl: 'https://picsum.photos/seed/hibiscus-red/600/400',
      categoryId: catMap.get('flowering-plants')!,
      climate: 'Tropical to Subtropical',
      elevation: '100-1200m',
      season: 'Year-round (peak: Summer-Monsoon)',
      sunlight: 'Full Sun',
      waterNeed: 'Moderate to High',
      soilType: 'Loamy to Sandy, well-draining',
      soilPH: '6.0-7.0',
      temperature: '18-38°C',
      humidity: '60-85%',
      matureHeight: '90-300cm',
      spread: '60-180cm',
      bloomTime: 'Year-round, peak March-October',
      difficulty: 'Easy',
      nutrients: 'NPK 10-20-10, Potassium-rich, Compost',
      fertilizer: 'Apply high-potassium fertilizer every 4-6 weeks in growing season to promote abundant blooms.',
      pruning: 'Prune in early spring to shape the plant and remove dead wood. Pinch tips for bushier growth.',
      propagation: 'Softwood cuttings in spring/monsoon. Also grows easily from seed.',
      companionPlants: 'Bougainvillea, Plumeria, Ixora',
      uses: 'Ornamental, Hedge, Tea, Hair Care, Landscaping',
      medicinalUses: 'Rich in vitamin C and antioxidants. Used to lower blood pressure, support liver health, and for hair growth.',
      edible: true,
      indoor: false,
      outdoor: true,
      fragrance: false,
      airPurifying: false,
      petSafe: true,
      inStock: true,
      stockCount: 90,
      featured: false,
      rating: 4.5,
      reviewCount: 108,
      tags: 'hibiscus, tropical, flowering, hedge, tea, ornamental',
    },
    {
      name: 'Bougainvillea',
      slug: 'bougainvillea',
      scientificName: 'Bougainvillea glabra',
      description: 'Bougainvillea transforms Nepali landscapes into cascades of vivid magenta, purple, orange, and white during the dry season. This hardy climbing vine thrives with neglect, making it perfect for busy gardeners. Often seen draping over walls and gates across Kathmandu, it\'s a symbol of resilience in Nepali horticulture.',
      shortDesc: 'Vibrant drought-tolerant climber that blankets walls in brilliant color.',
      price: 250,
      imageUrl: 'https://picsum.photos/seed/bougainvillea-magenta/600/400',
      categoryId: catMap.get('flowering-plants')!,
      climate: 'Subtropical to Tropical',
      elevation: '100-1500m',
      season: 'Dry Season (Oct-May)',
      sunlight: 'Full Sun',
      waterNeed: 'Low',
      soilType: 'Sandy to Loamy, well-draining, poor soil tolerated',
      soilPH: '5.5-7.0',
      temperature: '15-40°C',
      humidity: '30-70%',
      matureHeight: '300-900cm',
      spread: '150-450cm',
      bloomTime: 'October-May',
      difficulty: 'Easy',
      nutrients: 'Low nitrogen, High phosphorus, Potash',
      fertilizer: 'Apply bloom-boosting fertilizer (high phosphorus) sparingly every 6-8 weeks. Avoid excess nitrogen.',
      pruning: 'Prune aggressively after flowering cycle to maintain shape and promote new blooms. Wear gloves due to thorns.',
      propagation: 'Hardwood cuttings in spring. Very easy to root in well-draining medium.',
      companionPlants: 'Hibiscus, Plumeria, Allamanda',
      uses: 'Ornamental, Wall Cover, Hedge, Landscaping, Erosion Control',
      medicinalUses: 'Not commonly used medicinally, but traditional healers use leaves for respiratory issues.',
      edible: false,
      indoor: false,
      outdoor: true,
      fragrance: false,
      airPurifying: false,
      petSafe: false,
      inStock: true,
      stockCount: 110,
      featured: false,
      rating: 4.3,
      reviewCount: 74,
      tags: 'bougainvillea, climber, drought-tolerant, colorful, hardy, wall-cover',
    },
    {
      name: 'Lavender',
      slug: 'lavender',
      scientificName: 'Lavandula angustifolia',
      description: 'Lavender brings a touch of the Mediterranean to Nepali gardens with its soothing purple flower spikes and calming aroma. Growing well in Kathmandu Valley\'s cool winters and moderate summers, lavender is prized for its essential oil production. Its silvery foliage adds texture to garden borders even when not in bloom.',
      shortDesc: 'Aromatic purple spikes known for calming fragrance and essential oils.',
      price: 450,
      originalPrice: 550,
      imageUrl: 'https://picsum.photos/seed/lavender-purple/600/400',
      categoryId: catMap.get('flowering-plants')!,
      climate: 'Temperate',
      elevation: '1000-2500m',
      season: 'Spring-Summer',
      sunlight: 'Full Sun',
      waterNeed: 'Low to Moderate',
      soilType: 'Sandy, well-draining, alkaline',
      soilPH: '6.5-8.0',
      temperature: '10-25°C',
      humidity: '30-50%',
      matureHeight: '30-60cm',
      spread: '30-45cm',
      bloomTime: 'May-July',
      difficulty: 'Moderate',
      nutrients: 'Low nitrogen, Bone Meal, Lime',
      fertilizer: 'Minimal feeding required. Apply bone meal in spring. Avoid high-nitrogen fertilizers.',
      pruning: 'Prune back by one-third after flowering to maintain compact shape. Avoid cutting into old wood.',
      propagation: 'Softwood cuttings in spring, semi-hardwood cuttings in autumn. Seed germination is slow.',
      companionPlants: 'Rose, Sage, Thyme, Echinacea',
      uses: 'Ornamental, Aromatherapy, Essential Oil, Culinary, Potpourri, Soap Making',
      medicinalUses: 'Promotes sleep, reduces anxiety, antiseptic properties, relieves headaches. Used in Nepali spas.',
      edible: true,
      indoor: true,
      outdoor: true,
      fragrance: true,
      airPurifying: true,
      petSafe: false,
      inStock: true,
      stockCount: 40,
      featured: false,
      rating: 4.6,
      reviewCount: 67,
      tags: 'lavender, aromatic, calming, essential oil, temperate, purple',
    },
    {
      name: 'Amaryllis',
      slug: 'amaryllis',
      scientificName: 'Hippeastrum',
      description: 'Amaryllis produces magnificent large trumpet-shaped flowers in bold reds, whites, pinks, and striped varieties. These dramatic bulbs are popular gifts during Tihar and Christmas season in Nepal. Each bulb produces multiple flower stalks with 4-6 blooms each, creating a spectacular indoor display.',
      shortDesc: 'Dramatic trumpet-shaped blooms from bulbs, perfect for festive display.',
      price: 550,
      originalPrice: 680,
      imageUrl: 'https://picsum.photos/seed/amaryllis-red/600/400',
      categoryId: catMap.get('flowering-plants')!,
      climate: 'Subtropical to Temperate',
      elevation: '300-2000m',
      season: 'Winter-Spring',
      sunlight: 'Bright Indirect Light',
      waterNeed: 'Moderate',
      soilType: 'Loamy, well-draining, rich in organic matter',
      soilPH: '6.0-7.0',
      temperature: '18-25°C',
      humidity: '40-60%',
      matureHeight: '30-60cm',
      spread: '15-25cm',
      bloomTime: 'December-March',
      difficulty: 'Easy',
      nutrients: 'Phosphorus-rich fertilizer, Bone Meal, Potassium',
      fertilizer: 'Apply diluted liquid fertilizer every 2 weeks after growth starts. Stop when leaves begin to yellow.',
      pruning: 'Remove spent flower stalks at the base. Keep leaves intact to feed the bulb for next season.',
      propagation: 'Offset bulbs separated from the mother bulb during repotting. Can take 2-3 years to bloom from seed.',
      companionPlants: 'Peace Lily, Snake Plant, Rubber Plant',
      uses: 'Ornamental, Festive Decoration, Gift, Indoor Display, Cut Flowers',
      medicinalUses: 'Limited medicinal use. Contains alkaloids; not recommended for ingestion.',
      edible: false,
      indoor: true,
      outdoor: true,
      fragrance: false,
      airPurifying: false,
      petSafe: false,
      inStock: true,
      stockCount: 45,
      featured: false,
      rating: 4.4,
      reviewCount: 52,
      tags: 'amaryllis, bulb, festive, indoor, dramatic, winter-bloom',
    },

    // ── INDOOR PLANTS ─────────────────────────────────────────────
    {
      name: 'Peace Lily',
      slug: 'peace-lily',
      scientificName: 'Spathiphyllum wallisii',
      description: 'The Peace Lily is one of the best air-purifying houseplants, making it ideal for Kathmandu\'s polluted urban environment. Its elegant white spathes rise above glossy dark green leaves, blooming multiple times a year. This low-light tolerant plant is perfect for offices, bedrooms, and living rooms across Nepal.',
      shortDesc: 'Elegant air-purifying houseplant with graceful white blooms.',
      price: 450,
      originalPrice: 580,
      imageUrl: 'https://picsum.photos/seed/peace-lily-white/600/400',
      categoryId: catMap.get('indoor-plants')!,
      climate: 'Tropical',
      elevation: '100-1500m',
      season: 'Year-round',
      sunlight: 'Low to Bright Indirect Light',
      waterNeed: 'Moderate',
      soilType: 'Rich, well-draining potting mix with peat',
      soilPH: '5.5-6.5',
      temperature: '18-30°C',
      humidity: '50-70%',
      matureHeight: '30-90cm',
      spread: '30-60cm',
      bloomTime: 'Spring-Summer (can bloom year-round)',
      difficulty: 'Easy',
      nutrients: 'NPK 20-20-20, Liquid houseplant fertilizer',
      fertilizer: 'Feed with diluted liquid fertilizer every 6-8 weeks during growing season. Reduce in winter.',
      pruning: 'Remove yellowing leaves and spent flowers at the base. Wipe leaves to keep them clean and glossy.',
      propagation: 'Division of clumps during repotting. Separate sections with 3-4 leaves each.',
      companionPlants: 'Snake Plant, Pothos, ZZ Plant, Philodendron',
      uses: 'Ornamental, Air Purification, Office Plant, Gift, Interior Decor',
      medicinalUses: 'Primarily ornamental. Helps remove indoor air toxins like benzene, formaldehyde, and trichloroethylene.',
      edible: false,
      indoor: true,
      outdoor: false,
      fragrance: false,
      airPurifying: true,
      petSafe: false,
      inStock: true,
      stockCount: 65,
      featured: true,
      rating: 4.7,
      reviewCount: 143,
      tags: 'peace-lily, indoor, air-purifying, low-light, office, easy',
    },
    {
      name: 'Snake Plant',
      slug: 'snake-plant',
      scientificName: 'Sansevieria trifasciata',
      description: 'The Snake Plant, known locally as "Saanp ki Maa" or mother-in-law\'s tongue, is arguably the toughest indoor plant you can grow. Its striking upright sword-shaped leaves with variegated patterns add architectural interest to any room. NASA studies confirm it\'s one of the best plants for removing indoor air pollutants, especially at night.',
      shortDesc: 'Nearly indestructible air purifier with striking architectural leaves.',
      price: 380,
      originalPrice: 480,
      imageUrl: 'https://picsum.photos/seed/snake-plant-green/600/400',
      categoryId: catMap.get('indoor-plants')!,
      climate: 'Tropical to Subtropical',
      elevation: '100-2000m',
      season: 'Year-round',
      sunlight: 'Low Light to Bright Indirect',
      waterNeed: 'Low',
      soilType: 'Sandy, well-draining cactus/succulent mix',
      soilPH: '6.0-7.5',
      temperature: '15-35°C',
      humidity: '30-60%',
      matureHeight: '30-120cm',
      spread: '15-30cm',
      bloomTime: 'Rarely (when stressed)',
      difficulty: 'Easy',
      nutrients: 'Low feeding, NPK 10-10-10 diluted',
      fertilizer: 'Feed lightly 2-3 times during growing season. Over-fertilization causes more harm than under-feeding.',
      pruning: 'Minimal pruning needed. Remove damaged or yellowing leaves at the soil line with clean scissors.',
      propagation: 'Leaf cuttings (cut into 5cm segments), division of rhizomes, or water propagation.',
      companionPlants: 'Peace Lily, ZZ Plant, Pothos, Spider Plant',
      uses: 'Air Purification, Ornamental, Bedroom Plant, Office Plant, Feng Shui',
      medicinalUses: 'In Ayurveda, used for ear infections and skin wounds. Air purification is its primary health benefit.',
      edible: false,
      indoor: true,
      outdoor: true,
      fragrance: false,
      airPurifying: true,
      petSafe: false,
      inStock: true,
      stockCount: 80,
      featured: true,
      rating: 4.8,
      reviewCount: 198,
      tags: 'snake-plant, air-purifying, low-maintenance, indoor, drought-tolerant, nasa',
    },
    {
      name: 'Money Plant',
      slug: 'money-plant',
      scientificName: 'Epipremnum aureum (Pothos)',
      description: 'The Money Plant (Pothos) is the most popular houseplant in Nepal, believed to bring prosperity and good luck according to Vastu and Feng Shui. Its heart-shaped cascading leaves in green and golden varieties look stunning in hanging baskets and on shelves. Extremely forgiving of neglect, it grows in water or soil with equal ease.',
      shortDesc: 'Believed to bring good luck, this cascading vine thrives anywhere.',
      price: 180,
      originalPrice: 250,
      imageUrl: 'https://picsum.photos/seed/money-plant-pothos/600/400',
      categoryId: catMap.get('indoor-plants')!,
      climate: 'Tropical',
      elevation: '100-1500m',
      season: 'Year-round',
      sunlight: 'Low to Bright Indirect Light',
      waterChange: 'Low to Moderate',
      waterNeed: 'Low to Moderate',
      soilType: 'Any well-draining potting mix, or plain water',
      soilPH: '6.0-7.0',
      temperature: '18-32°C',
      humidity: '50-80%',
      matureHeight: 'Trailing 150-300cm',
      spread: '30-60cm',
      bloomTime: 'Rarely indoors',
      difficulty: 'Easy',
      nutrients: 'NPK 10-10-10, Liquid houseplant food',
      fertilizer: 'Feed monthly with diluted liquid fertilizer in growing season. Skip in winter.',
      pruning: 'Trim long vines to encourage bushier growth. Pinch growing tips. Propagate the trimmings!',
      propagation: 'Stem cuttings in water or soil. Roots appear in 1-2 weeks in water. Very high success rate.',
      companionPlants: 'Snake Plant, Peace Lily, Philodendron, Spider Plant',
      uses: 'Ornamental, Feng Shui, Air Purification, Hanging Baskets, Indoor Decor',
      medicinalUses: 'Used in traditional medicine for skin infections and wounds. Primarily grown for ornamental and cultural purposes.',
      edible: false,
      indoor: true,
      outdoor: true,
      fragrance: false,
      airPurifying: true,
      petSafe: false,
      inStock: true,
      stockCount: 150,
      featured: true,
      rating: 4.6,
      reviewCount: 187,
      tags: 'money-plant, pothos, feng-shui, indoor, trailing, easy, lucky',
    },
    {
      name: 'Rubber Plant',
      slug: 'rubber-plant',
      scientificName: 'Ficus elastica',
      description: 'The Rubber Plant is a statement indoor tree with large, glossy, burgundy or dark green leaves that instantly elevate any room\'s decor. Native to Northeast India and closely related to the rubber tree, it\'s well-suited to Nepal\'s climate. As it matures, it develops an elegant tree-like form with a thick trunk.',
      shortDesc: 'Bold glossy-leaved indoor tree that makes a dramatic statement.',
      price: 650,
      originalPrice: 800,
      imageUrl: 'https://picsum.photos/seed/rubber-ficus/600/400',
      categoryId: catMap.get('indoor-plants')!,
      climate: 'Tropical to Subtropical',
      elevation: '100-1200m',
      season: 'Year-round',
      sunlight: 'Bright Indirect Light',
      waterNeed: 'Moderate',
      soilType: 'Rich, well-draining potting mix with perlite',
      soilPH: '5.5-7.0',
      temperature: '16-30°C',
      humidity: '50-70%',
      matureHeight: '90-300cm (indoor)',
      spread: '60-120cm',
      bloomTime: 'Rarely indoors',
      difficulty: 'Easy',
      nutrients: 'NPK 3-1-2, Liquid houseplant fertilizer',
      fertilizer: 'Feed every 2 weeks in spring and summer with diluted liquid fertilizer. Stop in winter.',
      pruning: 'Prune to control height and encourage branching. Wear gloves as the sap is a skin irritant. Wipe leaves to maintain gloss.',
      propagation: 'Air layering is most reliable. Stem tip cuttings with rooting hormone also work.',
      companionPlants: 'Snake Plant, Monstera, ZZ Plant, Areca Palm',
      uses: 'Ornamental, Statement Plant, Air Purification, Interior Design, Feng Shui',
      medicinalUses: 'Ficus latex traditionally used for wound healing and skin conditions. Not recommended for home use.',
      edible: false,
      indoor: true,
      outdoor: true,
      fragrance: false,
      airPurifying: true,
      petSafe: false,
      inStock: true,
      stockCount: 40,
      featured: false,
      rating: 4.5,
      reviewCount: 91,
      tags: 'rubber-plant, ficus, indoor-tree, statement, glossy, air-purifying',
    },
    {
      name: 'Areca Palm',
      slug: 'areca-palm',
      scientificName: 'Dypsis lutescens',
      description: 'The Areca Palm, often called Butterfly Palm, brings a lush tropical feel to indoor spaces with its feathery arching fronds. It\'s rated by NASA as one of the top air-purifying plants, effectively removing xylene and toluene. In Nepal, it\'s a popular choice for hotel lobbies, offices, and spacious living rooms.',
      shortDesc: 'Lush tropical palm that purifies air and adds resort-like vibes.',
      price: 800,
      originalPrice: 1000,
      imageUrl: 'https://picsum.photos/seed/areca-palm-tropical/600/400',
      categoryId: catMap.get('indoor-plants')!,
      climate: 'Tropical to Subtropical',
      elevation: '100-1000m',
      season: 'Year-round',
      sunlight: 'Bright Indirect Light',
      waterNeed: 'Moderate to High',
      soilType: 'Well-draining, peat-based potting mix',
      soilPH: '6.0-6.5',
      temperature: '18-32°C',
      humidity: '60-80%',
      matureHeight: '150-300cm (indoor)',
      spread: '90-180cm',
      bloomTime: 'Rarely indoors',
      difficulty: 'Moderate',
      nutrients: 'NPK 12-4-12, Magnesium, Manganese',
      fertilizer: 'Feed monthly with liquid palm fertilizer during growing season. Add Epsom salt for magnesium.',
      pruning: 'Remove brown fronds at the base with clean shears. Do not cut green fronds. Mist regularly in dry conditions.',
      propagation: 'Division of offshoots (pups) at the base. Seed propagation is slow and less common.',
      companionPlants: 'Snake Plant, Peace Lily, Boston Fern, Philodendron',
      uses: 'Ornamental, Air Purification, Humidifier, Privacy Screen, Interior Landscaping',
      medicinalUses: 'Not directly medicinal. Its air-purifying and humidifying qualities contribute to respiratory health.',
      edible: false,
      indoor: true,
      outdoor: true,
      fragrance: false,
      airPurifying: true,
      petSafe: true,
      inStock: true,
      stockCount: 30,
      featured: false,
      rating: 4.4,
      reviewCount: 78,
      tags: 'areca-palm, palm, indoor, air-purifying, tropical, humidity, lobby',
    },

    // ── HERBS & SPICES ────────────────────────────────────────────
    {
      name: 'Tulsi (Holy Basil)',
      slug: 'tulsi-holy-basil',
      scientificName: 'Ocimum tenuiflorum',
      description: 'Tulsi is the most sacred plant in Hindu tradition, found in the courtyard of nearly every Nepali home. This aromatic herb comes in two main varieties — green (Rama) and purple (Krishna) — both revered for their medicinal properties. Regular consumption of Tulsi tea boosts immunity and is a cornerstone of Ayurvedic wellness.',
      shortDesc: 'Sacred Ayurvedic herb revered for immunity-boosting medicinal properties.',
      price: 150,
      imageUrl: 'https://picsum.photos/seed/tulsi-basil/600/400',
      categoryId: catMap.get('herbs-spices')!,
      climate: 'Subtropical to Tropical',
      elevation: '100-1800m',
      season: 'Spring-Autumn',
      sunlight: 'Full Sun',
      waterNeed: 'Moderate',
      soilType: 'Loamy, well-draining, rich in organic matter',
      soilPH: '6.0-7.5',
      temperature: '20-35°C',
      humidity: '50-70%',
      matureHeight: '30-60cm',
      spread: '20-30cm',
      bloomTime: 'June-September',
      difficulty: 'Easy',
      nutrients: 'NPK 5-5-5, Compost, Cow Manure',
      fertilizer: 'Apply compost or diluted cow manure every 4-6 weeks. Avoid chemical fertilizers for medicinal use.',
      pruning: 'Pinch flower buds regularly to promote leafy growth. Harvest leaves from the top. Prune woody stems in spring.',
      propagation: 'Seeds sown in spring, stem cuttings in warm weather. Very easy to propagate and naturalize.',
      companionPlants: 'Tomato, Chili, Pepper, Marigold',
      uses: 'Medicinal, Tea, Culinary, Religious, Immunity Booster, Essential Oil',
      medicinalUses: 'Powerful adaptogen. Treats cold, cough, fever, stress, diabetes, and respiratory disorders. Antioxidant, anti-inflammatory, and antimicrobial properties.',
      edible: true,
      indoor: true,
      outdoor: true,
      fragrance: true,
      airPurifying: true,
      petSafe: true,
      inStock: true,
      stockCount: 200,
      featured: true,
      rating: 4.9,
      reviewCount: 203,
      tags: 'tulsi, holy basil, sacred, ayurvedic, medicinal, tea, immunity',
    },
    {
      name: 'Mint',
      slug: 'mint',
      scientificName: 'Mentha spicata',
      description: 'Fresh mint is an essential kitchen herb in Nepali cuisine, used in chutneys, achaar, mojitos, and garnishes. Its vigorous spreading habit makes it both a blessing and a challenge — it quickly fills any space it\'s given. The cool, refreshing aroma is released at the slightest touch, making it a sensory delight in any herb garden.',
      shortDesc: 'Vigorous, refreshing herb essential for Nepali chutneys and drinks.',
      price: 120,
      imageUrl: 'https://picsum.photos/seed/mint-fresh/600/400',
      categoryId: catMap.get('herbs-spices')!,
      climate: 'Temperate to Subtropical',
      elevation: '200-2200m',
      season: 'Spring-Autumn',
      sunlight: 'Partial Shade to Full Sun',
      waterNeed: 'High',
      soilType: 'Rich, moist, well-draining soil',
      soilPH: '6.0-7.0',
      temperature: '15-30°C',
      humidity: '60-80%',
      matureHeight: '20-60cm',
      spread: '30-90cm (aggressive spreader)',
      bloomTime: 'June-September',
      difficulty: 'Easy',
      nutrients: 'NPK 10-10-10, Nitrogen-rich, Compost',
      fertilizer: 'Apply nitrogen-rich fertilizer or compost every 4-6 weeks. Mint is a heavy feeder.',
      pruning: 'Harvest frequently to prevent flowering and encourage bushy growth. Cut back by half in midsummer.',
      propagation: 'Stem cuttings root in water within days. Also spreads by runners and division.',
      companionPlants: 'Tomato, Cabbage, Peas, Basil',
      uses: 'Culinary, Chutney, Tea, Beverages, Garnish, Aromatherapy',
      medicinalUses: 'Aids digestion, relieves headaches, clears congestion, freshens breath. Anti-inflammatory and antispasmodic.',
      edible: true,
      indoor: true,
      outdoor: true,
      fragrance: true,
      airPurifying: true,
      petSafe: true,
      inStock: true,
      stockCount: 120,
      featured: false,
      rating: 4.5,
      reviewCount: 156,
      tags: 'mint, herb, kitchen, culinary, refreshing, chutney, easy',
    },
    {
      name: 'Lemongrass',
      slug: 'lemongrass',
      scientificName: 'Cymbopogon citratus',
      description: 'Lemongrass is a tall, aromatic grass that fills the garden with its citrusy scent and is indispensable in Nepali and Thai cooking. Its stalks are used to flavor teas, soups, and curries, while its essential oil is a natural mosquito repellent. Growing in dense clumps, it also serves as an attractive ornamental grass in garden borders.',
      shortDesc: 'Citrusy aromatic grass for cooking, tea, and natural pest control.',
      price: 200,
      imageUrl: 'https://picsum.photos/seed/lemongrass-citrus/600/400',
      categoryId: catMap.get('herbs-spices')!,
      climate: 'Tropical to Subtropical',
      elevation: '100-1200m',
      season: 'Year-round',
      sunlight: 'Full Sun',
      waterNeed: 'Moderate to High',
      soilType: 'Loamy, rich, well-draining',
      soilPH: '6.0-7.0',
      temperature: '20-38°C',
      humidity: '60-85%',
      matureHeight: '60-150cm',
      spread: '45-90cm',
      bloomTime: 'Rarely flowers',
      difficulty: 'Easy',
      nutrients: 'NPK 10-10-10, Nitrogen-rich, Compost',
      fertilizer: 'Apply nitrogen-rich fertilizer monthly during growing season. Compost tea works well.',
      pruning: 'Harvest outer stalks at ground level. Cut back the entire clump to 10cm in early spring for fresh growth.',
      propagation: 'Division of clumps is easiest. Also grows from store-bought stalks rooted in water.',
      companionPlants: 'Basil, Mint, Tomatoes, Citrus',
      uses: 'Culinary, Tea, Essential Oil, Mosquito Repellent, Ornamental Grass',
      medicinalUses: 'Relieves anxiety, aids digestion, reduces fever, antimicrobial properties. Tea helps with cold and flu symptoms.',
      edible: true,
      indoor: true,
      outdoor: true,
      fragrance: true,
      airPurifying: true,
      petSafe: true,
      inStock: true,
      stockCount: 70,
      featured: false,
      rating: 4.4,
      reviewCount: 89,
      tags: 'lemongrass, citrus, culinary, tea, mosquito-repellent, aromatic',
    },
    {
      name: 'Turmeric',
      slug: 'turmeric',
      scientificName: 'Curcuma longa',
      description: 'Turmeric is the golden spice of Nepal, deeply embedded in the country\'s culinary and cultural traditions. Beyond its vibrant color and warm flavor in curries, turmeric\'s active compound curcumin has powerful anti-inflammatory and antioxidant properties. Growing your own turmeric is rewarding — harvest the rhizomes after 8-10 months.',
      shortDesc: 'Golden health-boosting spice with powerful anti-inflammatory properties.',
      price: 250,
      imageUrl: 'https://picsum.photos/seed/turmeric-root/600/400',
      categoryId: catMap.get('herbs-spices')!,
      climate: 'Tropical to Subtropical',
      elevation: '100-1200m',
      season: 'Spring planted, Autumn harvested',
      sunlight: 'Partial Shade to Full Sun',
      waterNeed: 'High',
      soilType: 'Rich, loamy, well-draining with high organic content',
      soilPH: '5.5-7.0',
      temperature: '20-35°C',
      humidity: '70-90%',
      matureHeight: '60-100cm',
      spread: '30-60cm',
      bloomTime: 'July-September',
      difficulty: 'Easy',
      nutrients: 'NPK 10-20-10, Phosphorus, Potassium, Compost, Cow Manure',
      fertilizer: 'Apply well-rotted compost and cow manure at planting. Side-dress with potassium-rich fertilizer monthly.',
      pruning: 'Minimal pruning. Remove dead leaves. Cut flower stalks if you want to redirect energy to rhizome production.',
      propagation: 'Plant rhizome pieces (with 2-3 buds) 5cm deep in spring. Each piece produces multiple new rhizomes.',
      companionPlants: 'Ginger, Lemongrass, Chili, Tomato',
      uses: 'Culinary, Spice, Medicine, Natural Dye, Skincare, Religious Ceremonies',
      medicinalUses: 'Anti-inflammatory, antioxidant, aids digestion, boosts immunity, supports joint health, promotes wound healing. Curcumin is extensively studied for cancer prevention.',
      edible: true,
      indoor: false,
      outdoor: true,
      fragrance: true,
      airPurifying: false,
      petSafe: true,
      inStock: true,
      stockCount: 95,
      featured: false,
      rating: 4.6,
      reviewCount: 112,
      tags: 'turmeric, spice, golden, anti-inflammatory, curcumin, culinary, ayurvedic',
    },
    {
      name: 'Coriander',
      slug: 'coriander',
      scientificName: 'Coriandrum sativum',
      description: 'Coriander (Dhania) is the most used herb in Nepali kitchens, essential for achaar, chutneys, dal, and garnishing almost every dish. Both the fresh leaves (cilantro) and dried seeds are used in cooking. It grows quickly from seed and does best in the cooler months in Kathmandu, bolting quickly in summer heat.',
      shortDesc: 'Must-have kitchen herb for garnishing and flavoring Nepali dishes.',
      price: 100,
      imageUrl: 'https://picsum.photos/seed/coriander-herb/600/400',
      categoryId: catMap.get('herbs-spices')!,
      climate: 'Subtropical to Temperate',
      elevation: '300-2500m',
      season: 'Autumn-Spring (cool weather)',
      sunlight: 'Full Sun to Partial Shade',
      waterNeed: 'Moderate',
      soilType: 'Loamy, well-draining, rich in organic matter',
      soilPH: '6.0-7.0',
      temperature: '15-25°C',
      humidity: '50-70%',
      matureHeight: '20-50cm',
      spread: '10-25cm',
      bloomTime: 'Spring (when it bolts)',
      difficulty: 'Easy',
      nutrients: 'NPK 10-10-10, Nitrogen, Compost',
      fertilizer: 'Light feeding with nitrogen-rich fertilizer every 3-4 weeks. Too much fertilizer reduces flavor.',
      pruning: 'Harvest outer leaves regularly to delay bolting. Once it flowers, let it go to seed for coriander seeds.',
      propagation: 'Direct sow seeds every 2-3 weeks for continuous harvest. Does not transplant well.',
      companionPlants: 'Tomato, Chili, Basil, Parsley',
      uses: 'Culinary, Garnish, Chutney, Seed Spice, Achaar',
      medicinalUses: 'Aids digestion, lowers blood sugar, rich in antioxidants and vitamins A, C, K. Seeds used for digestive issues.',
      edible: true,
      indoor: true,
      outdoor: true,
      fragrance: true,
      airPurifying: false,
      petSafe: true,
      inStock: true,
      stockCount: 180,
      featured: false,
      rating: 4.3,
      reviewCount: 134,
      tags: 'coriander, cilantro, dhania, kitchen, herb, garnish, easy',
    },

    // ── VEGETABLES ────────────────────────────────────────────────
    {
      name: 'Tomato',
      slug: 'tomato',
      scientificName: 'Solanum lycopersicum',
      description: 'Tomatoes are the most popular home-grown vegetable in Nepal, thriving in gardens from Terai to the mid-hills. Fresh homegrown tomatoes far surpass store-bought ones in flavor and nutrition. They come in diverse varieties — from cherry tomatoes for salads to large beefsteak types for curries.',
      shortDesc: 'The most rewarding home vegetable with unmatched fresh flavor.',
      price: 180,
      imageUrl: 'https://picsum.photos/seed/tomato-red/600/400',
      categoryId: catMap.get('vegetables')!,
      climate: 'Subtropical to Temperate',
      elevation: '100-2000m',
      season: 'Spring-Summer',
      sunlight: 'Full Sun',
      waterNeed: 'High',
      soilType: 'Loamy, well-draining, rich in organic matter',
      soilPH: '6.0-6.8',
      temperature: '20-30°C',
      humidity: '50-70%',
      matureHeight: '60-180cm (depending on variety)',
      spread: '45-90cm',
      bloomTime: 'March-June',
      difficulty: 'Moderate',
      nutrients: 'NPK 5-10-10, Calcium, Phosphorus, Compost',
      fertilizer: 'Start with phosphorus-rich fertilizer at planting. Side-dress with calcium-rich fertilizer to prevent blossom end rot.',
      pruning: 'Remove suckers between main stem and branches for indeterminate varieties. Stake or cage for support.',
      propagation: 'Seeds started indoors 6-8 weeks before last frost. Transplant when 15cm tall.',
      companionPlants: 'Basil, Marigold, Carrot, Garlic',
      uses: 'Culinary, Salad, Curry, Chutney, Sauce, Juice',
      medicinalUses: 'Rich in lycopene (antioxidant), vitamin C, potassium. Supports heart health and may reduce cancer risk.',
      edible: true,
      indoor: false,
      outdoor: true,
      fragrance: true,
      airPurifying: false,
      petSafe: false,
      inStock: true,
      stockCount: 100,
      featured: false,
      rating: 4.4,
      reviewCount: 145,
      tags: 'tomato, vegetable, home-grown, salad, curry, summer, garden',
    },
    {
      name: 'Chili',
      slug: 'chili',
      scientificName: 'Capsicum annuum',
      description: 'Green and red chilies are fundamental to Nepali cuisine, providing the heat that makes dal-bhat-tarkari so irresistible. Nepal grows many local varieties from mild to extremely hot. Homegrown chilies are far more flavorful and aromatic than market-bought ones, making them a must-grow for any kitchen garden.',
      shortDesc: 'Essential spicy staple that brings heat and flavor to every Nepali meal.',
      price: 150,
      imageUrl: 'https://picsum.photos/seed/chili-pepper/600/400',
      categoryId: catMap.get('vegetables')!,
      climate: 'Subtropical to Tropical',
      elevation: '100-1800m',
      season: 'Spring-Autumn',
      sunlight: 'Full Sun',
      waterNeed: 'Moderate to High',
      soilType: 'Loamy, well-draining, rich in organic matter',
      soilPH: '6.0-6.8',
      temperature: '22-35°C',
      humidity: '50-70%',
      matureHeight: '45-90cm',
      spread: '30-60cm',
      bloomTime: 'April-September',
      difficulty: 'Easy',
      nutrients: 'NPK 5-10-10, Phosphorus, Calcium, Compost',
      fertilizer: 'Apply phosphorus-rich fertilizer at planting. Feed every 3-4 weeks with balanced fertilizer during fruiting.',
      pruning: 'Pinch first flowers to encourage bushier growth. Remove dead leaves. Support with stakes if needed.',
      propagation: 'Seeds sown indoors in late winter, transplanted after frost danger passes. Soak seeds overnight for faster germination.',
      companionPlants: 'Tomato, Basil, Garlic, Carrot',
      uses: 'Culinary, Spice, Pickle, Achaar, Drying, Sauce',
      medicinalUses: 'Rich in capsaicin which boosts metabolism, relieves pain, and has anti-inflammatory properties. High in vitamin C.',
      edible: true,
      indoor: false,
      outdoor: true,
      fragrance: false,
      airPurifying: false,
      petSafe: false,
      inStock: true,
      stockCount: 110,
      featured: false,
      rating: 4.5,
      reviewCount: 167,
      tags: 'chili, pepper, spicy, vegetable, nepali-cuisine, achaar, essential',
    },

    // ── FRUIT PLANTS ──────────────────────────────────────────────
    {
      name: 'Mango',
      slug: 'mango',
      scientificName: 'Mangifera indica',
      description: 'The mango is known as the king of fruits in Nepal, with the Terai region producing some of the finest varieties. From the early-season "Malda" to the late-season "Langra," Nepali mangoes are celebrated for their sweetness and rich flavor. A grafted mango tree begins bearing fruit in 3-4 years and can produce for decades.',
      shortDesc: 'King of fruits — a grafted tree that rewards you for decades.',
      price: 2500,
      originalPrice: 3000,
      imageUrl: 'https://picsum.photos/seed/mango-tree/600/400',
      categoryId: catMap.get('fruit-plants')!,
      climate: 'Tropical to Subtropical',
      elevation: '100-800m',
      season: 'Spring (planting), Summer (fruiting)',
      sunlight: 'Full Sun',
      waterNeed: 'Moderate',
      soilType: 'Deep, well-draining loamy soil',
      soilPH: '5.5-7.5',
      temperature: '25-38°C',
      humidity: '50-80%',
      matureHeight: '600-1500cm',
      spread: '600-1200cm',
      bloomTime: 'December-February (flowers), May-July (fruit)',
      difficulty: 'Moderate',
      nutrients: 'NPK 8-4-8, Compost, Bone Meal, Zinc',
      fertilizer: 'Apply compost and balanced NPK 3-4 times per year. Increase potassium during fruiting. Apply zinc sulfate for better yields.',
      pruning: 'Prune in the first 2-3 years to establish a strong framework. Remove dead or crossing branches. Thinning of fruit clusters improves size.',
      propagation: 'Grafting (veneer grafting is most common) on local seedling rootstock. Seed-grown trees take 6-8 years to fruit.',
      companionPlants: 'Lemongrass, Basil, Beans, Clover',
      uses: 'Fruit, Juice, Pickle (Achaar), Desserts, Shade Tree, Landscaping',
      medicinalUses: 'Rich in vitamins A, C, and fiber. Supports digestion, boosts immunity, and has antioxidant properties.',
      edible: true,
      indoor: false,
      outdoor: true,
      fragrance: true,
      airPurifying: false,
      petSafe: false,
      inStock: true,
      stockCount: 15,
      featured: false,
      rating: 4.7,
      reviewCount: 43,
      tags: 'mango, fruit-tree, tropical, grafted, terai, king-of-fruits',
    },
    {
      name: 'Lemon',
      slug: 'lemon',
      scientificName: 'Citrus limon',
      description: 'Lemon trees are a practical and beautiful addition to any Nepali garden, providing year-round supply of fresh lemons for cooking, tea, and traditional remedies. The fragrant white blossoms are an added bonus. "Kagaji" lemons thrive particularly well in the mid-hills, producing abundant thin-skinned, juicy fruit.',
      shortDesc: 'Productive citrus tree providing fresh lemons and fragrant blossoms.',
      price: 1200,
      originalPrice: 1500,
      imageUrl: 'https://picsum.photos/seed/lemon-citrus/600/400',
      categoryId: catMap.get('fruit-plants')!,
      climate: 'Subtropical',
      elevation: '300-1500m',
      season: 'Year-round (peak fruiting: Oct-Feb)',
      sunlight: 'Full Sun',
      waterNeed: 'Moderate',
      soilType: 'Well-draining, slightly acidic loam',
      soilPH: '5.5-6.5',
      temperature: '15-35°C',
      humidity: '50-70%',
      matureHeight: '300-500cm',
      spread: '300-450cm',
      bloomTime: 'Year-round, peak in spring',
      difficulty: 'Moderate',
      nutrients: 'NPK 6-4-6, Citrus-specific fertilizer, Zinc, Iron',
      fertilizer: 'Apply citrus-specific fertilizer 3 times per year. Add iron chelate if leaves show yellowing with green veins.',
      pruning: 'Prune after harvest to remove dead wood and shape the canopy. Remove suckers from below the graft union.',
      propagation: 'Grafting on rough lemon rootstock. Air layering also works. Seed-grown trees take longer to bear.',
      companionPlants: 'Marigold, Basil, Comfrey, Peas',
      uses: 'Culinary, Juice, Tea, Pickle, Cleaning, Fragrance, Skincare',
      medicinalUses: 'Rich in vitamin C. Boosts immunity, aids digestion, prevents scurvy. Used in traditional remedies for cold and sore throat.',
      edible: true,
      indoor: false,
      outdoor: true,
      fragrance: true,
      airPurifying: false,
      petSafe: false,
      inStock: true,
      stockCount: 20,
      featured: false,
      rating: 4.5,
      reviewCount: 56,
      tags: 'lemon, citrus, fruit-tree, kagaji, juice, versatile, mid-hills',
    },

    // ── SUCCULENTS & CACTI ────────────────────────────────────────
    {
      name: 'Aloe Vera',
      slug: 'aloe-vera',
      scientificName: 'Aloe barbadensis miller',
      description: 'Aloe Vera is nature\'s first-aid kit, found in almost every Nepali household for treating burns, skin ailments, and digestive issues. This succulent requires minimal care and reproduces enthusiastically through offsets. Its thick gel-filled leaves are a treasure trove of vitamins, minerals, and amino acids used in beauty and health products worldwide.',
      shortDesc: 'Nature\'s healing succulent — a living first-aid kit for skin and health.',
      price: 280,
      originalPrice: 350,
      imageUrl: 'https://picsum.photos/seed/aloe-vera-green/600/400',
      categoryId: catMap.get('succulents-cacti')!,
      climate: 'Tropical to Subtropical',
      elevation: '100-1500m',
      season: 'Year-round',
      sunlight: 'Bright Indirect to Full Sun',
      waterNeed: 'Low',
      soilType: 'Sandy, well-draining cactus/succulent mix',
      soilPH: '6.5-7.5',
      temperature: '15-38°C',
      humidity: '30-50%',
      matureHeight: '30-60cm',
      spread: '30-60cm',
      bloomTime: 'Winter-Spring (orange/yellow flowers)',
      difficulty: 'Easy',
      nutrients: 'Low feeding, NPK 10-10-10 diluted to half strength',
      fertilizer: 'Feed once in spring and once in summer with diluted liquid fertilizer. Do not feed in winter.',
      pruning: 'Harvest outer mature leaves at the base for gel. Remove dried or damaged leaves. Separate offsets to control spread.',
      propagation: 'Separate offsets (pups) from the base when they have 4-5 leaves. Allow cut ends to dry before planting.',
      companionPlants: 'Jade Plant, Snake Plant, Echeveria, Haworthia',
      uses: 'Medicinal, Skincare, Haircare, First-Aid, Juice, Ornamental',
      medicinalUses: 'Treats burns, wounds, and skin conditions. Aids digestion when consumed as juice. Anti-inflammatory, antimicrobial, antioxidant. Supports immune system and blood sugar regulation.',
      edible: true,
      indoor: true,
      outdoor: true,
      fragrance: false,
      airPurifying: true,
      petSafe: false,
      inStock: true,
      stockCount: 85,
      featured: true,
      rating: 4.8,
      reviewCount: 176,
      tags: 'aloe-vera, succulent, healing, skincare, medicinal, low-maintenance',
    },
    {
      name: 'Jade Plant',
      slug: 'jade-plant',
      scientificName: 'Crassula ovata',
      description: 'The Jade Plant is a symbol of prosperity and good fortune in Nepali and Chinese culture, making it a popular gift and home accent. Its thick, oval-shaped, glossy green leaves resemble jade coins, and with proper care, it can live for decades. Mature plants produce charming clusters of star-shaped pink-white flowers in winter.',
      shortDesc: 'Lucky succulent with coin-like leaves that can live for decades.',
      price: 350,
      originalPrice: 450,
      imageUrl: 'https://picsum.photos/seed/jade-plant-succulent/600/400',
      categoryId: catMap.get('succulents-cacti')!,
      climate: 'Subtropical to Temperate',
      elevation: '100-2000m',
      season: 'Year-round',
      sunlight: 'Bright Indirect to Full Sun',
      waterNeed: 'Low',
      soilType: 'Sandy, well-draining succulent/cactus mix',
      soilPH: '6.0-7.0',
      temperature: '12-28°C',
      humidity: '30-50%',
      matureHeight: '30-100cm',
      spread: '30-60cm',
      bloomTime: 'Winter (mature plants)',
      difficulty: 'Easy',
      nutrients: 'Low feeding, NPK 10-10-10 at half strength',
      fertilizer: 'Feed 2-3 times during spring and summer with diluted liquid fertilizer. Do not fertilize in winter.',
      pruning: 'Minimal pruning needed. Prune to shape or control size. Pinch tips for bushier growth on young plants.',
      propagation: 'Leaf or stem cuttings. Allow cut ends to dry for 2-3 days before placing on soil. Very high success rate.',
      companionPlants: 'Aloe Vera, Echeveria, Snake Plant, Haworthia',
      uses: 'Ornamental, Feng Shui, Gift, Bonsai, Desk Plant',
      medicinalUses: 'In traditional medicine, used for warts, skin ulcers, and digestive issues. Not recommended for internal use without supervision.',
      edible: false,
      indoor: true,
      outdoor: true,
      fragrance: false,
      airPurifying: false,
      petSafe: false,
      inStock: true,
      stockCount: 55,
      featured: false,
      rating: 4.5,
      reviewCount: 94,
      tags: 'jade-plant, succulent, lucky, feng-shui, bonsai, coin-plant, long-lived',
    },

    // ── TREES & SHRUBS ────────────────────────────────────────────
    {
      name: 'Neem',
      slug: 'neem',
      scientificName: 'Azadirachta indica',
      description: 'Neem is revered as the "village pharmacy" in Nepal and across South Asia, with every part of the tree — leaves, bark, seeds, and flowers — having medicinal value. This fast-growing evergreen tree provides shade, acts as a natural pesticide, and is deeply rooted in Ayurvedic tradition. Neem trees are commonly planted near homes for their purifying and protective qualities.',
      shortDesc: 'Sacred "village pharmacy" tree with unmatched medicinal versatility.',
      price: 500,
      imageUrl: 'https://picsum.photos/seed/neem-tree/600/400',
      categoryId: catMap.get('trees-shrubs')!,
      climate: 'Tropical to Subtropical',
      elevation: '100-1200m',
      season: 'Year-round',
      sunlight: 'Full Sun',
      waterNeed: 'Low to Moderate',
      soilType: 'Any well-draining soil, drought-tolerant once established',
      soilPH: '6.2-7.5',
      temperature: '20-42°C',
      humidity: '30-70%',
      matureHeight: '1000-1500cm',
      spread: '800-1200cm',
      bloomTime: 'March-May',
      difficulty: 'Easy',
      nutrients: 'NPK 10-10-10, Compost, Organic matter',
      fertilizer: 'Apply compost or well-rotted manure annually around the base. Young trees benefit from balanced fertilizer.',
      pruning: 'Prune young trees to establish a strong central leader. Remove dead or damaged branches. Minimal pruning needed once established.',
      propagation: 'Seeds (fresh seeds germinate in 1-2 weeks), semi-hardwood cuttings. Direct sowing in monsoon is common.',
      companionPlants: 'Turmeric, Basil, Lemongrass, Marigold',
      uses: 'Medicinal, Shade, Natural Pesticide, Timber, Fertilizer (neem cake), Firewood',
      medicinalUses: 'Antibacterial, antifungal, antiviral, anti-inflammatory, and antipyretic. Treats skin disorders, malaria, diabetes, digestive issues. Neem oil used for hair and skin care. Neem tea boosts immunity.',
      edible: false,
      indoor: false,
      outdoor: true,
      fragrance: false,
      airPurifying: true,
      petSafe: true,
      inStock: true,
      stockCount: 25,
      featured: false,
      rating: 4.7,
      reviewCount: 67,
      tags: 'neem, tree, medicinal, ayurvedic, shade, pesticide, village-pharmacy',
    },
  ]

  // Remove invalid field before inserting
  const cleanedPlants = plantsData.map(({ waterChange: _, ...plant }) => plant)

  const plants = []
  for (const plant of cleanedPlants) {
    const created = await db.plant.create({ data: plant })
    plants.push(created)
    console.log(`  ✅ ${created.name} (${created.slug})`)
  }

  console.log(`\n🌱 Seeding complete!`)
  console.log(`   📦 Categories: ${categories.length}`)
  console.log(`   🌿 Plants: ${plants.length}`)
  console.log(`   ⭐ Featured plants: ${plants.filter((p) => p.featured).length}`)
  console.log(`   💰 Price range: NPR ${Math.min(...plants.map((p) => p.price))} - NPR ${Math.max(...plants.map((p) => p.price))}`)
}

main()
  .then(async () => {
    await db.$disconnect()
  })
  .catch(async (e) => {
    console.error('❌ Seeding failed:', e)
    await db.$disconnect()
    process.exit(1)
  })