import { PrismaClient } from "@prisma/client";
import { pbkdf2Sync, randomBytes } from "crypto";

const prisma = new PrismaClient();

function hashPassword(password: string): string {
  const PBKDF2_ITERATIONS = 100000;
  const PBKDF2_KEYLEN = 64;
  const PBKDF2_DIGEST = "sha512";
  const salt = randomBytes(16);
  const derivedKey = pbkdf2Sync(password, salt, PBKDF2_ITERATIONS, PBKDF2_KEYLEN, PBKDF2_DIGEST);
  return `${PBKDF2_ITERATIONS}:${salt.toString("hex")}:${derivedKey.toString("hex")}`;
}

async function main() {
  const username = process.env.ADMIN_USERNAME || "admin";
  const password = process.env.ADMIN_PASSWORD || "admin123";
  const passwordHash = hashPassword(password);

  const admin = await prisma.adminUser.upsert({
    where: { username },
    update: { passwordHash },
    create: { username, passwordHash, role: "admin" },
  });
  console.log(`✅ Admin user "${admin.username}" ready`);

  // ===== CATEGORIES =====
  const categories = [
    { name: "Flowering Plants", slug: "flowering-plants", icon: "Flower2", description: "Beautiful flowering plants for gardens and homes", order: 0 },
    { name: "Indoor Plants", slug: "indoor-plants", icon: "Home", description: "Low-maintenance plants perfect for indoor spaces", order: 1 },
    { name: "Herbs & Spices", slug: "herbs-spices", icon: "Leaf", description: "Fresh herbs and spice plants for your kitchen garden", order: 2 },
    { name: "Vegetables", slug: "vegetables", icon: "Carrot", description: "Vegetable seedlings and plants for home gardening", order: 3 },
    { name: "Fruit Plants", slug: "fruit-plants", icon: "Apple", description: "Fruit-bearing plants and trees for Nepali gardens", order: 4 },
    { name: "Succulents & Cacti", slug: "succulents-cacti", icon: "Cactus", description: "Drought-tolerant succulents and decorative cacti", order: 5 },
    { name: "Trees & Shrubs", slug: "trees-shrubs", icon: "TreePine", description: "Ornamental and shade trees, evergreen shrubs", order: 6 },
    { name: "Medicinal Plants", slug: "medicinal-plants", icon: "Heart", description: "Traditional Ayurvedic and medicinal plants", order: 7 },
    { name: "Fertilizers & Nutrients", slug: "fertilizers-nutrients", icon: "FlaskConical", description: "Plant fertilizers, nutrients, and growth supplements", order: 8 },
    { name: "Pots & Equipment", slug: "pots-equipment", icon: "Shovel", description: "Plant pots, tools, and gardening equipment", order: 9 },
  ];

  const createdCategories: Record<string, string> = {};
  for (const cat of categories) {
    const created = await prisma.category.upsert({
      where: { slug: cat.slug },
      update: { name: cat.name, description: cat.description, icon: cat.icon, order: cat.order },
      create: cat,
    });
    createdCategories[cat.slug] = created.id;
    console.log(`  📁 Category: ${cat.name}`);
  }

  // ===== PLANTS =====
  const plants: Array<{
    name: string;
    slug: string;
    scientificName: string;
    description: string;
    shortDesc: string;
    price: number;
    originalPrice?: number;
    imageUrl: string;
    categorySlug: string;
    climate: string;
    elevation: string;
    season: string;
    sunlight: string;
    waterNeed: string;
    soilType: string;
    soilPH?: string;
    temperature: string;
    humidity?: string;
    matureHeight?: string;
    spread?: string;
    bloomTime?: string;
    difficulty: string;
    nutrients: string;
    fertilizer?: string;
    pruning?: string;
    propagation?: string;
    companionPlants?: string;
    uses: string;
    medicinalUses?: string;
    edible: boolean;
    indoor: boolean;
    outdoor: boolean;
    fragrance: boolean;
    airPurifying: boolean;
    petSafe: boolean;
    stockCount: number;
    featured: boolean;
    unit: string;
  }> = [
    // ===== FLOWERING PLANTS =====
    {
      name: "Rhododendron (Lali Gurans)",
      slug: "rhododendron-lali-gurans",
      scientificName: "Rhododendron arboreum",
      description: "The national flower of Nepal, Rhododendron is a stunning evergreen shrub that produces spectacular clusters of bell-shaped flowers in shades of red, pink, and white. Found naturally in the mid-hill forests of Nepal, this iconic plant thrives in cool, misty conditions and adds magnificent color to any garden from March to May.",
      shortDesc: "Nepal's national flower with vibrant red blooms",
      price: 850,
      originalPrice: 1200,
      imageUrl: "https://images.unsplash.com/photo-1490750967868-88aa4f44baee?w=600&h=400&fit=crop",
      categorySlug: "flowering-plants",
      climate: "Subtropical to Temperate",
      elevation: "1500-3600m",
      season: "Spring",
      sunlight: "Partial Shade",
      waterNeed: "Moderate",
      soilType: "Loamy, well-draining",
      soilPH: "4.5-6.0",
      temperature: "5-20°C",
      humidity: "60-80%",
      matureHeight: "5-15m",
      spread: "3-6m",
      bloomTime: "March - May",
      difficulty: "Moderate",
      nutrients: "Nitrogen, Phosphorus, Potassium",
      fertilizer: "Acidic fertilizer, twice in growing season",
      pruning: "Prune after flowering to maintain shape",
      propagation: "Seeds, cuttings, layering",
      companionPlants: "Azaleas, Camellias, Ferns",
      uses: "Ornamental, National symbol, Garden landscaping",
      medicinalUses: "Flowers used in traditional medicine for diarrhea and inflammation",
      edible: false,
      indoor: false,
      outdoor: true,
      fragrance: true,
      airPurifying: false,
      petSafe: false,
      stockCount: 25,
      featured: true,
    },
    {
      name: "Hibiscus (Jaba)",
      slug: "hibiscus-jaba",
      scientificName: "Hibiscus rosa-sinensis",
      description: "A tropical flowering shrub prized for its large, showy flowers that bloom continuously throughout the year in warm climates. Available in vibrant shades of red, orange, pink, yellow, and white. Easy to grow and maintain, hibiscus is perfect for Nepali gardens and balconies.",
      shortDesc: "Year-round tropical blooms in vibrant colors",
      price: 350,
      originalPrice: 500,
      imageUrl: "https://images.unsplash.com/photo-1558171813-4c088753af8f?w=600&h=400&fit=crop",
      categorySlug: "flowering-plants",
      climate: "Tropical, Subtropical",
      elevation: "100-1500m",
      season: "Year-round",
      sunlight: "Full Sun",
      waterNeed: "Moderate",
      soilType: "Loamy, well-draining",
      temperature: "15-35°C",
      humidity: "50-70%",
      matureHeight: "1.5-3m",
      spread: "1-2m",
      bloomTime: "Year-round",
      difficulty: "Easy",
      nutrients: "Potassium, Phosphorus",
      fertilizer: "Balanced NPK monthly",
      pruning: "Pinch tips for bushy growth, prune in spring",
      propagation: "Stem cuttings",
      companionPlants: "Bougainvillea, Plumeria, Lantana",
      uses: "Ornamental, Tea, Hair care",
      medicinalUses: "Rich in Vitamin C, used for hair growth and blood pressure",
      edible: true,
      indoor: false,
      outdoor: true,
      fragrance: true,
      airPurifying: false,
      petSafe: true,
      stockCount: 40,
      featured: true,
    },
    {
      name: "Bougainvillea",
      slug: "bougainvillea",
      scientificName: "Bougainvillea glabra",
      description: "A vigorous, drought-tolerant climbing plant that produces masses of vibrant papery bracts in magenta, purple, orange, and white. One of the most popular ornamental plants in Nepal, perfect for covering walls, fences, and arches with a stunning cascade of color.",
      shortDesc: "Vibrant climbing plant with masses of color",
      price: 280,
      imageUrl: "https://images.unsplash.com/photo-1599419448312-a36fa6e5e92a?w=600&h=400&fit=crop",
      categorySlug: "flowering-plants",
      climate: "Tropical, Subtropical",
      elevation: "100-2000m",
      season: "Year-round",
      sunlight: "Full Sun",
      waterNeed: "Low",
      soilType: "Sandy, well-draining",
      temperature: "10-40°C",
      matureHeight: "3-10m",
      spread: "2-5m",
      bloomTime: "September - March",
      difficulty: "Easy",
      nutrients: "Phosphorus, Potassium",
      fertilizer: "Low nitrogen, high phosphorus",
      pruning: "Prune heavily after flowering",
      propagation: "Stem cuttings",
      uses: "Ornamental, Wall covering, Landscaping",
      edible: false,
      indoor: false,
      outdoor: true,
      fragrance: false,
      airPurifying: false,
      petSafe: true,
      stockCount: 35,
      featured: false,
    },
    {
      name: "Plumeria (Champa)",
      slug: "plumeria-champa",
      scientificName: "Plumeria rubra",
      description: "Known as the temple flower, Plumeria produces beautiful fragrant flowers in white, pink, yellow, and red. Widely used in religious offerings across Nepal and South Asia. The sweet fragrance is especially strong at night, making it a beloved garden plant.",
      shortDesc: "Fragrant temple flowers with heavenly scent",
      price: 450,
      originalPrice: 600,
      imageUrl: "https://images.unsplash.com/photo-1604068549290-dea0e4a305ca?w=600&h=400&fit=crop",
      categorySlug: "flowering-plants",
      climate: "Tropical, Subtropical",
      elevation: "100-1500m",
      season: "Spring - Autumn",
      sunlight: "Full Sun",
      waterNeed: "Low to Moderate",
      soilType: "Sandy loam",
      temperature: "15-35°C",
      matureHeight: "3-8m",
      spread: "2-4m",
      bloomTime: "April - October",
      difficulty: "Easy",
      nutrients: "Phosphorus, Potassium",
      fertilizer: "Low nitrogen, bloom booster",
      propagation: "Stem cuttings",
      uses: "Religious offerings, Garland making, Fragrance",
      medicinalUses: "Bark used for skin diseases, anti-inflammatory",
      edible: false,
      indoor: false,
      outdoor: true,
      fragrance: true,
      airPurifying: false,
      petSafe: false,
      stockCount: 20,
      featured: true,
    },

    // ===== INDOOR PLANTS =====
    {
      name: "Snake Plant (Sansevieria)",
      slug: "snake-plant-sansevieria",
      scientificName: "Sansevieria trifasciata",
      description: "One of the most resilient indoor plants, the Snake Plant thrives on neglect. Its upright, sword-like leaves add architectural interest to any room. NASA studies confirm it's one of the best air-purifying plants, removing formaldehyde, benzene, and other toxins. Perfect for offices and bedrooms.",
      shortDesc: "NASA-certified air purifier, nearly indestructible",
      price: 320,
      originalPrice: 450,
      imageUrl: "https://images.unsplash.com/photo-1593482892580-e32e47e0a48a?w=600&h=400&fit=crop",
      categorySlug: "indoor-plants",
      climate: "Tropical, Subtropical",
      elevation: "0-2000m",
      season: "Year-round",
      sunlight: "Low Light to Indirect",
      waterNeed: "Low",
      soilType: "Sandy, well-draining",
      temperature: "15-30°C",
      humidity: "30-50%",
      matureHeight: "0.3-1.5m",
      spread: "0.3-0.6m",
      difficulty: "Easy",
      nutrients: "Nitrogen, Potassium",
      fertilizer: "Light feeding in summer",
      propagation: "Leaf cuttings, division",
      uses: "Air purification, Ornamental, Feng Shui",
      medicinalUses: "Used for wound healing, air purifier",
      edible: false,
      indoor: true,
      outdoor: false,
      fragrance: false,
      airPurifying: true,
      petSafe: false,
      stockCount: 55,
      featured: true,
    },
    {
      name: "Peace Lily",
      slug: "peace-lily",
      scientificName: "Spathiphyllum wallisii",
      description: "An elegant indoor plant with glossy dark green leaves and graceful white spathe flowers. One of the best plants for removing indoor air pollutants including benzene, formaldehyde, and ammonia. Thrives in low light conditions, making it perfect for homes and offices in Nepal.",
      shortDesc: "Elegant white blooms, thrives in low light",
      price: 380,
      imageUrl: "https://images.unsplash.com/photo-1616690002178-4b10e0c87947?w=600&h=400&fit=crop",
      categorySlug: "indoor-plants",
      climate: "Tropical",
      elevation: "0-1000m",
      season: "Year-round",
      sunlight: "Low to Medium Indirect",
      waterNeed: "Moderate",
      soilType: "Peat-based, well-draining",
      temperature: "18-30°C",
      humidity: "50-70%",
      matureHeight: "0.3-0.6m",
      spread: "0.3-0.5m",
      bloomTime: "Spring - Autumn",
      difficulty: "Easy",
      nutrients: "Nitrogen, Phosphorus",
      fertilizer: "Balanced liquid fertilizer monthly",
      propagation: "Division",
      uses: "Air purification, Decorative, Gifting",
      medicinalUses: "Air purifier, removes VOCs",
      edible: false,
      indoor: true,
      outdoor: false,
      fragrance: true,
      airPurifying: true,
      petSafe: false,
      stockCount: 30,
      featured: true,
    },
    {
      name: "Money Plant (Golden Pothos)",
      slug: "money-plant-golden-pothos",
      scientificName: "Epipremnum aureum",
      description: "The most popular indoor plant in Nepal, the Money Plant is a trailing vine with heart-shaped golden-variegated leaves. Believed to bring good luck and prosperity in Feng Shui. Extremely easy to grow in water or soil, it's perfect for hanging baskets, shelves, and desktops.",
      shortDesc: "Bring home good luck with this easy grower",
      price: 150,
      imageUrl: "https://images.unsplash.com/photo-1572688484438-313a56e6a939?w=600&h=400&fit=crop",
      categorySlug: "indoor-plants",
      climate: "Tropical, Subtropical",
      elevation: "0-2000m",
      season: "Year-round",
      sunlight: "Low to Bright Indirect",
      waterNeed: "Low to Moderate",
      soilType: "Any well-draining",
      temperature: "15-30°C",
      matureHeight: "Trailing 2m+",
      spread: "0.3-1m",
      difficulty: "Easy",
      nutrients: "Nitrogen",
      fertilizer: "Light feeding monthly",
      propagation: "Stem cuttings in water",
      uses: "Ornamental, Air purification, Feng Shui",
      medicinalUses: "Air purifier, removes formaldehyde",
      edible: false,
      indoor: true,
      outdoor: true,
      fragrance: false,
      airPurifying: true,
      petSafe: false,
      stockCount: 80,
      featured: true,
    },
    {
      name: "ZZ Plant (Zanzibar Gem)",
      slug: "zz-plant-zanzibar-gem",
      scientificName: "Zamioculcas zamiifolia",
      description: "A virtually indestructible indoor plant with glossy, dark green, waxy leaves. The ZZ Plant can survive in very low light and needs very little water, making it perfect for busy people or offices. Its architectural form adds a modern touch to any interior space.",
      shortDesc: "Virtually indestructible, perfect for offices",
      price: 420,
      imageUrl: "https://images.unsplash.com/photo-1609170952465-2aedf31e3b5c?w=600&h=400&fit=crop",
      categorySlug: "indoor-plants",
      climate: "Tropical",
      elevation: "0-1500m",
      season: "Year-round",
      sunlight: "Low to Medium Indirect",
      waterNeed: "Very Low",
      soilType: "Well-draining potting mix",
      temperature: "15-28°C",
      humidity: "30-50%",
      matureHeight: "0.5-1m",
      spread: "0.4-0.8m",
      difficulty: "Easy",
      nutrients: "General purpose",
      fertilizer: "2-3 times per year",
      propagation: "Leaf cuttings, division",
      uses: "Office plant, Decorative, Low maintenance",
      medicinalUses: "Air purifier",
      edible: false,
      indoor: true,
      outdoor: false,
      fragrance: false,
      airPurifying: true,
      petSafe: false,
      stockCount: 25,
      featured: false,
    },

    // ===== HERBS & SPICES =====
    {
      name: "Tulsi (Holy Basil)",
      slug: "tulsi-holy-basil",
      scientificName: "Ocimum tenuiflorum",
      description: "The most sacred plant in Hindu tradition, Tulsi is an aromatic herb with powerful medicinal properties. Rich in antioxidants and essential oils, it's used daily in Nepali households for making herbal tea, religious offerings, and Ayurvedic remedies. Easy to grow in pots or gardens.",
      shortDesc: "Sacred medicinal herb for every home",
      price: 80,
      imageUrl: "https://images.unsplash.com/photo-1628556270448-4d4e4148e1b1?w=600&h=400&fit=crop",
      categorySlug: "herbs-spices",
      climate: "Tropical, Subtropical",
      elevation: "0-1800m",
      season: "Year-round",
      sunlight: "Full Sun",
      waterNeed: "Moderate",
      soilType: "Loamy, fertile",
      temperature: "20-35°C",
      matureHeight: "0.3-0.6m",
      spread: "0.2-0.4m",
      bloomTime: "Summer",
      difficulty: "Easy",
      nutrients: "Nitrogen, Phosphorus",
      fertilizer: "Organic compost monthly",
      propagation: "Seeds, cuttings",
      uses: "Tea, Religious, Culinary, Ayurveda",
      medicinalUses: "Immunity booster, stress relief, respiratory health, anti-inflammatory",
      edible: true,
      indoor: true,
      outdoor: true,
      fragrance: true,
      airPurifying: true,
      petSafe: true,
      stockCount: 100,
      featured: true,
    },
    {
      name: "Mint (Pudina)",
      slug: "mint-pudina",
      scientificName: "Mentha spicata",
      description: "A fast-growing, aromatic herb that's essential in Nepali cuisine. Mint leaves are used in chutneys, teas, salads, and as a garnish. Extremely easy to grow, it spreads quickly in garden beds or containers. The refreshing aroma makes it a wonderful kitchen garden plant.",
      shortDesc: "Fresh aromatic herb for kitchen gardens",
      price: 60,
      imageUrl: "https://images.unsplash.com/photo-1628556270416-2ff8b5df6b80?w=600&h=400&fit=crop",
      categorySlug: "herbs-spices",
      climate: "Temperate, Subtropical",
      elevation: "0-2500m",
      season: "Spring - Autumn",
      sunlight: "Partial Shade to Full Sun",
      waterNeed: "High",
      soilType: "Moist, rich loam",
      temperature: "15-30°C",
      matureHeight: "0.2-0.5m",
      spread: "Spreading",
      bloomTime: "Summer",
      difficulty: "Easy",
      nutrients: "Nitrogen",
      fertilizer: "Liquid fertilizer every 2 weeks",
      propagation: "Stem cuttings, runners",
      uses: "Culinary, Tea, Mouth freshener, Chutney",
      medicinalUses: "Digestion, headache relief, nausea",
      edible: true,
      indoor: true,
      outdoor: true,
      fragrance: true,
      airPurifying: false,
      petSafe: true,
      stockCount: 90,
      featured: false,
    },
    {
      name: "Lemongrass",
      slug: "lemongrass",
      scientificName: "Cymbopogon citratus",
      description: "A tall, aromatic grass widely used in Asian cuisine and traditional medicine. Its fresh, citrusy scent repels mosquitoes naturally. Lemongrass is a key ingredient in Nepali tea (chiya) and soups. Very easy to grow and maintain in Nepali climate.",
      shortDesc: "Citrus-scented herb that repels mosquitoes",
      price: 120,
      imageUrl: "https://images.unsplash.com/photo-1588165171080-c89acfa5ee83?w=600&h=400&fit=crop",
      categorySlug: "herbs-spices",
      climate: "Tropical, Subtropical",
      elevation: "0-1500m",
      season: "Year-round",
      sunlight: "Full Sun",
      waterNeed: "Moderate to High",
      soilType: "Rich, well-draining",
      temperature: "20-35°C",
      matureHeight: "0.5-1.5m",
      spread: "0.5-1m",
      difficulty: "Easy",
      nutrients: "Nitrogen",
      fertilizer: "Organic compost",
      propagation: "Division, stem cuttings",
      uses: "Tea, Cooking, Mosquito repellent, Aromatherapy",
      medicinalUses: "Fever reducer, digestive aid, antibacterial",
      edible: true,
      indoor: false,
      outdoor: true,
      fragrance: true,
      airPurifying: false,
      petSafe: true,
      stockCount: 45,
      featured: false,
    },

    // ===== VEGETABLES =====
    {
      name: "Tomato (Golbheda)",
      slug: "tomato-golbheda",
      scientificName: "Solanum lycopersicum",
      description: "The most popular vegetable for home gardening in Nepal. Tomatoes are versatile, nutritious, and relatively easy to grow. They thrive in the Nepali climate and produce abundant harvests from nursery-raised seedlings. Perfect for balcony gardens and kitchen gardens.",
      shortDesc: "Essential home garden vegetable, easy to grow",
      price: 50,
      imageUrl: "https://images.unsplash.com/photo-1592841200221-a6898f307baa?w=600&h=400&fit=crop",
      categorySlug: "vegetables",
      climate: "Subtropical, Temperate",
      elevation: "0-2000m",
      season: "Spring - Autumn",
      sunlight: "Full Sun",
      waterNeed: "Moderate to High",
      soilType: "Rich, well-draining loam",
      temperature: "20-30°C",
      matureHeight: "0.5-2m",
      spread: "0.4-0.8m",
      bloomTime: "Summer",
      difficulty: "Easy",
      nutrients: "Nitrogen, Phosphorus, Potassium, Calcium",
      fertilizer: "NPK 10-10-10, add calcium",
      pruning: "Remove suckers, stake plants",
      propagation: "Seeds",
      companionPlants: "Basil, Marigold, Carrots",
      uses: "Cooking, Salads, Pickles, Chutney",
      medicinalUses: "Rich in lycopene, Vitamin C, antioxidant",
      edible: true,
      indoor: false,
      outdoor: true,
      fragrance: true,
      airPurifying: false,
      petSafe: false,
      stockCount: 120,
      featured: false,
    },
    {
      name: "Chili Pepper (Khursani)",
      slug: "chili-pepper-khursani",
      scientificName: "Capsicum annuum",
      description: "A must-have in every Nepali kitchen garden! Green and red chilies are essential ingredients in Nepali cuisine. These plants produce abundant harvests of spicy peppers throughout the growing season. Compact varieties work well in pots and containers.",
      shortDesc: "Essential spice for every Nepali kitchen",
      price: 45,
      imageUrl: "https://images.unsplash.com/photo-1588252303782-cb80119abd6d?w=600&h=400&fit=crop",
      categorySlug: "vegetables",
      climate: "Tropical, Subtropical",
      elevation: "0-1500m",
      season: "Spring - Autumn",
      sunlight: "Full Sun",
      waterNeed: "Moderate",
      soilType: "Loamy, well-draining",
      temperature: "20-35°C",
      matureHeight: "0.3-1m",
      spread: "0.3-0.5m",
      bloomTime: "Summer",
      difficulty: "Easy",
      nutrients: "Phosphorus, Potassium",
      fertilizer: "Low nitrogen, high PK",
      propagation: "Seeds",
      companionPlants: "Tomatoes, Basil, Carrots",
      uses: "Cooking, Pickle (Achar), Spice",
      medicinalUses: "Rich in capsaicin, boosts metabolism, pain relief",
      edible: true,
      indoor: false,
      outdoor: true,
      fragrance: false,
      airPurifying: false,
      petSafe: false,
      stockCount: 100,
      featured: false,
    },
    {
      name: "Coriander (Dhania)",
      slug: "coriander-dhania",
      scientificName: "Coriandrum sativum",
      description: "One of the most essential herbs in Nepali cooking, coriander leaves (cilantro) are used as garnish in almost every dish. The seeds are also used as a spice (dhania). Fast-growing and can be harvested multiple times from a single planting.",
      shortDesc: "Essential garnish herb for Nepali cooking",
      price: 40,
      imageUrl: "https://images.unsplash.com/photo-1515586838455-8f8f940d6853?w=600&h=400&fit=crop",
      categorySlug: "vegetables",
      climate: "Subtropical, Temperate",
      elevation: "0-2000m",
      season: "Spring, Autumn",
      sunlight: "Full Sun to Partial Shade",
      waterNeed: "Moderate",
      soilType: "Loamy, well-draining",
      temperature: "15-28°C",
      matureHeight: "0.3-0.6m",
      spread: "0.15-0.3m",
      bloomTime: "Summer",
      difficulty: "Easy",
      nutrients: "Nitrogen",
      fertilizer: "Light organic feeding",
      propagation: "Seeds",
      uses: "Garnish, Chutney, Spice seeds, Curry",
      medicinalUses: "Aids digestion, lowers blood sugar, antioxidant",
      edible: true,
      indoor: true,
      outdoor: true,
      fragrance: true,
      airPurifying: false,
      petSafe: true,
      stockCount: 150,
      featured: false,
    },

    // ===== FRUIT PLANTS =====
    {
      name: "Mango (Aam)",
      slug: "mango-aam",
      scientificName: "Mangifera indica",
      description: "The king of fruits! Nepal's Terai region produces excellent mangoes. Growing your own mango tree is a rewarding long-term investment. Choose grafted varieties for faster fruiting. The tree provides delicious fruit and cooling shade for your garden.",
      shortDesc: "King of fruits - grow your own mango tree",
      price: 1200,
      originalPrice: 1800,
      imageUrl: "https://images.unsplash.com/photo-1553279768-865429fa0078?w=600&h=400&fit=crop",
      categorySlug: "fruit-plants",
      climate: "Tropical, Subtropical",
      elevation: "0-1200m",
      season: "Summer",
      sunlight: "Full Sun",
      waterNeed: "Moderate",
      soilType: "Deep, well-draining loam",
      temperature: "20-40°C",
      matureHeight: "10-30m",
      spread: "8-15m",
      bloomTime: "February - March",
      difficulty: "Moderate",
      nutrients: "Nitrogen, Phosphorus, Potassium",
      fertilizer: "NPK balanced, organic compost",
      pruning: "Prune young trees for shape",
      propagation: "Grafting, seeds (grafting preferred)",
      uses: "Fruit, Shade, Pickle (Achar), Juice",
      medicinalUses: "Rich in Vitamin A, C, aids digestion",
      edible: true,
      indoor: false,
      outdoor: true,
      fragrance: true,
      airPurifying: false,
      petSafe: false,
      stockCount: 8,
      featured: true,
    },
    {
      name: "Strawberry",
      slug: "strawberry",
      scientificName: "Fragaria × ananassa",
      description: "Strawberries grow beautifully in Nepal's hill regions, particularly around Kathmandu valley and higher elevations. These runner-producing plants can be grown in beds, containers, or hanging baskets. Nothing beats the taste of freshly picked homegrown strawberries!",
      shortDesc: "Sweet hill-grown berries for pots and gardens",
      price: 200,
      imageUrl: "https://images.unsplash.com/photo-1464965911861-746a04b4bca6?w=600&h=400&fit=crop",
      categorySlug: "fruit-plants",
      climate: "Temperate",
      elevation: "1000-2500m",
      season: "Spring - Summer",
      sunlight: "Full Sun",
      waterNeed: "Moderate to High",
      soilType: "Rich, slightly acidic",
      soilPH: "5.5-6.5",
      temperature: "10-25°C",
      matureHeight: "0.15-0.3m",
      spread: "0.3-0.5m (runners)",
      bloomTime: "Spring",
      difficulty: "Moderate",
      nutrients: "Phosphorus, Potassium",
      fertilizer: "Balanced, low nitrogen",
      propagation: "Runners, division",
      uses: "Fresh fruit, Jam, Desserts, Juice",
      medicinalUses: "Rich in Vitamin C, antioxidants, fiber",
      edible: true,
      indoor: false,
      outdoor: true,
      fragrance: false,
      airPurifying: false,
      petSafe: true,
      stockCount: 60,
      featured: true,
    },
    {
      name: "Lemon (Kagati)",
      slug: "lemon-kagati",
      scientificName: "Citrus limon",
      description: "An essential fruit tree for every Nepali home garden. Lemons are used daily in cooking, as a health remedy, and in religious ceremonies. Compact varieties are available that are perfect for container growing on balconies and terraces.",
      shortDesc: "Essential citrus tree for every home",
      price: 550,
      imageUrl: "https://images.unsplash.com/photo-1590502593747-42a996133562?w=600&h=400&fit=crop",
      categorySlug: "fruit-plants",
      climate: "Subtropical",
      elevation: "0-1500m",
      season: "Year-round",
      sunlight: "Full Sun",
      waterNeed: "Moderate",
      soilType: "Well-draining, slightly acidic",
      temperature: "15-35°C",
      matureHeight: "3-6m",
      spread: "2-4m",
      bloomTime: "Spring, Autumn",
      difficulty: "Easy",
      nutrients: "Nitrogen, Phosphorus, Potassium, Zinc",
      fertilizer: "Citrus fertilizer, 3x per year",
      propagation: "Grafting, cuttings",
      uses: "Cooking, Tea, Health tonic, Religious",
      medicinalUses: "Vitamin C, immune booster, aids digestion",
      edible: true,
      indoor: false,
      outdoor: true,
      fragrance: true,
      airPurifying: false,
      petSafe: false,
      stockCount: 18,
      featured: false,
    },

    // ===== SUCCULENTS & CACTI =====
    {
      name: "Aloe Vera (Ghiu Kumari)",
      slug: "aloe-vera-ghiu-kumari",
      scientificName: "Aloe barbadensis miller",
      description: "Known as 'Ghiu Kumari' in Nepali, Aloe Vera is a miracle plant with countless uses. The gel inside its fleshy leaves is used for skin care, hair care, and as a health drink. It's incredibly easy to grow, requires minimal water, and reproduces freely through pups.",
      shortDesc: "Miracle plant for skin, hair, and health",
      price: 180,
      imageUrl: "https://images.unsplash.com/photo-1509423350716-97f9360b4e09?w=600&h=400&fit=crop",
      categorySlug: "succulents-cacti",
      climate: "Tropical, Arid",
      elevation: "0-2000m",
      season: "Year-round",
      sunlight: "Bright Indirect to Full Sun",
      waterNeed: "Very Low",
      soilType: "Sandy, well-draining",
      temperature: "10-40°C",
      matureHeight: "0.3-0.8m",
      spread: "0.3-0.6m",
      bloomTime: "Winter - Spring",
      difficulty: "Easy",
      nutrients: "Low requirements",
      fertilizer: "Once or twice a year",
      propagation: "Pups (offsets)",
      uses: "Skin care, Hair care, Health drink, Burns",
      medicinalUses: "Wound healing, skin conditions, digestive aid, anti-inflammatory",
      edible: true,
      indoor: true,
      outdoor: true,
      fragrance: false,
      airPurifying: true,
      petSafe: false,
      stockCount: 70,
      featured: true,
    },
    {
      name: "Echeveria",
      slug: "echeveria",
      scientificName: "Echeveria elegans",
      description: "A stunning rosette-forming succulent with plump, silvery-green leaves tipped in pink. One of the most popular ornamental succulents worldwide, perfect for desk plants, fairy gardens, and succulent arrangements. Extremely drought-tolerant and low-maintenance.",
      shortDesc: "Beautiful rosette succulent for desk decor",
      price: 250,
      imageUrl: "https://images.unsplash.com/photo-1459411552884-841db9b3cc2a?w=600&h=400&fit=crop",
      categorySlug: "succulents-cacti",
      climate: "Arid, Semi-arid",
      elevation: "0-2500m",
      season: "Year-round",
      sunlight: "Bright Light to Full Sun",
      waterNeed: "Very Low",
      soilType: "Sandy, gritty, well-draining",
      temperature: "10-30°C",
      matureHeight: "0.05-0.15m",
      spread: "0.1-0.2m",
      bloomTime: "Spring - Summer",
      difficulty: "Easy",
      nutrients: "Low requirements",
      fertilizer: "Succulent fertilizer, dilute, monthly in summer",
      propagation: "Leaf cuttings, offsets, beheading",
      uses: "Decorative, Desk plant, Arrangements",
      medicinalUses: "Minimal, primarily ornamental",
      edible: false,
      indoor: true,
      outdoor: true,
      fragrance: false,
      airPurifying: true,
      petSafe: true,
      stockCount: 45,
      featured: false,
    },
    {
      name: "Jade Plant (Money Tree)",
      slug: "jade-plant-money-tree",
      scientificName: "Crassula ovata",
      description: "A symbol of prosperity and good fortune, the Jade Plant is a popular succulent with thick, oval-shaped, glossy green leaves that develop red edges in full sun. Long-lived and easy to care for, it can grow into a small tree over decades. Often passed down as a family heirloom.",
      shortDesc: "Symbol of prosperity, lives for decades",
      price: 300,
      imageUrl: "https://images.unsplash.com/photo-1509423350716-97f9360b4e09?w=600&h=400&fit=crop",
      categorySlug: "succulents-cacti",
      climate: "Subtropical",
      elevation: "0-2000m",
      season: "Year-round",
      sunlight: "Bright Light",
      waterNeed: "Very Low",
      soilType: "Sandy, well-draining",
      temperature: "10-30°C",
      matureHeight: "0.3-1m (can reach 2m over years)",
      spread: "0.3-0.6m",
      bloomTime: "Winter (with proper care)",
      difficulty: "Easy",
      nutrients: "Low requirements",
      fertilizer: "2-3 times per year",
      propagation: "Stem/leaf cuttings",
      uses: "Ornamental, Bonsai, Feng Shui, Gifting",
      medicinalUses: "Wound healing in traditional medicine",
      edible: false,
      indoor: true,
      outdoor: true,
      fragrance: false,
      airPurifying: true,
      petSafe: false,
      stockCount: 35,
      featured: false,
    },

    // ===== TREES & SHRUBS =====
    {
      name: "Neem Tree (Nim)",
      slug: "neem-tree-nim",
      scientificName: "Azadirachta indica",
      description: "The 'village pharmacy' - every part of the Neem tree has medicinal value. A fast-growing, evergreen tree that provides excellent shade and purifies the air. Neem is deeply rooted in Nepali and Indian culture for its healing properties. An essential tree for any large garden.",
      shortDesc: "The village pharmacy - nature's medicine cabinet",
      price: 350,
      imageUrl: "https://images.unsplash.com/photo-1542273917363-3b1817f69a2d?w=600&h=400&fit=crop",
      categorySlug: "trees-shrubs",
      climate: "Tropical, Subtropical",
      elevation: "0-1500m",
      season: "Year-round (deciduous in dry season)",
      sunlight: "Full Sun",
      waterNeed: "Low once established",
      soilType: "Any well-draining",
      temperature: "15-45°C",
      matureHeight: "15-20m",
      spread: "8-15m",
      bloomTime: "Spring",
      difficulty: "Easy",
      nutrients: "Low requirements",
      fertilizer: "Organic compost annually",
      propagation: "Seeds, cuttings",
      uses: "Medicine, Shade, Pest control, Air purification",
      medicinalUses: "Antibacterial, antifungal, antiviral, antipyretic, skin diseases, malaria",
      edible: false,
      indoor: false,
      outdoor: true,
      fragrance: false,
      airPurifying: true,
      petSafe: true,
      stockCount: 12,
      featured: false,
    },
    {
      name: "Bamboo (Bans)",
      slug: "bamboo-bans",
      scientificName: "Bambusa vulgaris",
      description: "An iconic plant in Nepali culture and architecture, bamboo is one of the fastest-growing plants on Earth. It provides building material, food (bamboo shoots), and excellent soil erosion control on hillsides. Multiple clumping varieties available that won't spread invasively.",
      shortDesc: "Fast-growing, multi-purpose Nepali staple",
      price: 400,
      imageUrl: "https://images.unsplash.com/photo-1500471875778-a3e4cd585957?w=600&h=400&fit=crop",
      categorySlug: "trees-shrubs",
      climate: "Tropical, Subtropical, Temperate",
      elevation: "0-3000m",
      season: "Year-round (evergreen)",
      sunlight: "Full Sun to Partial Shade",
      waterNeed: "Moderate to High",
      soilType: "Loamy, moisture-retentive",
      temperature: "10-40°C",
      matureHeight: "5-15m",
      spread: "2-5m (clumping type)",
      bloomTime: "Rarely (decades)",
      difficulty: "Easy",
      nutrients: "Nitrogen",
      fertilizer: "Organic compost, high nitrogen",
      propagation: "Division, rhizome cuttings",
      uses: "Construction, Furniture, Food, Erosion control",
      medicinalUses: "Bamboo shoots nutritious, silica for bone health",
      edible: true,
      indoor: false,
      outdoor: true,
      fragrance: false,
      airPurifying: true,
      petSafe: true,
      stockCount: 15,
      featured: false,
    },
    {
      name: "Japanese Maple",
      slug: "japanese-maple",
      scientificName: "Acer palmatum",
      description: "A stunning ornamental tree prized for its delicate, deeply-lobed leaves that turn brilliant shades of red, orange, and gold in autumn. Perfect for Nepali hill gardens and temple courtyards. A slow grower that becomes more beautiful with each passing year.",
      shortDesc: "Stunning autumn foliage for hill gardens",
      price: 1500,
      originalPrice: 2200,
      imageUrl: "https://images.unsplash.com/photo-1509773896068-7fd415d91e2e?w=600&h=400&fit=crop",
      categorySlug: "trees-shrubs",
      climate: "Temperate",
      elevation: "1000-2500m",
      season: "Spring - Autumn (best color in fall)",
      sunlight: "Partial Shade",
      waterNeed: "Moderate",
      soilType: "Acidic, well-draining, rich",
      soilPH: "5.5-6.5",
      temperature: "5-25°C",
      matureHeight: "4-8m",
      spread: "3-6m",
      bloomTime: "Spring (inconspicuous)",
      difficulty: "Moderate",
      nutrients: "Balanced, slow-release",
      fertilizer: "Slow-release in spring",
      pruning: "Minimal, winter pruning only",
      propagation: "Grafting, seeds",
      uses: "Ornamental, Bonsai, Garden centerpiece",
      medicinalUses: "Primarily ornamental",
      edible: false,
      indoor: false,
      outdoor: true,
      fragrance: false,
      airPurifying: false,
      petSafe: true,
      stockCount: 5,
      featured: true,
    },

    // ===== MEDICINAL PLANTS =====
    {
      name: "Amla (Indian Gooseberry)",
      slug: "amla-indian-gooseberry",
      scientificName: "Phyllanthus emblica",
      description: "Known as 'Amala' in Nepali, this is one of the most important plants in Ayurvedic medicine. The small, sour fruits are the richest natural source of Vitamin C. Used in chyawanprash, hair oils, and traditional remedies. A medium-sized deciduous tree with feathery foliage.",
      shortDesc: "Richest natural Vitamin C source, Ayurvedic superfood",
      price: 450,
      imageUrl: "https://images.unsplash.com/photo-1615485290382-441e4d049cb5?w=600&h=400&fit=crop",
      categorySlug: "medicinal-plants",
      climate: "Subtropical, Tropical",
      elevation: "0-1500m",
      season: "Winter (fruiting)",
      sunlight: "Full Sun",
      waterNeed: "Moderate",
      soilType: "Loamy, well-draining",
      temperature: "15-45°C",
      matureHeight: "5-10m",
      spread: "3-6m",
      bloomTime: "Spring",
      difficulty: "Easy",
      nutrients: "Organic compost",
      fertilizer: "Organic compost annually",
      propagation: "Seeds, grafting",
      uses: "Medicine, Food, Hair oil, Chyawanprash",
      medicinalUses: "Highest Vitamin C, anti-aging, immunity, digestion, hair growth, diabetes",
      edible: true,
      indoor: false,
      outdoor: true,
      fragrance: false,
      airPurifying: false,
      petSafe: true,
      stockCount: 20,
      featured: false,
    },
    {
      name: "Ashwagandha",
      slug: "ashwagandha",
      scientificName: "Withania somnifera",
      description: "One of the most powerful herbs in Ayurvedic medicine, Ashwagandha is an adaptogen that helps the body manage stress. The roots are used in powders, teas, and supplements. Easy to grow in Nepal's climate, this small shrub is increasingly popular worldwide.",
      shortDesc: "Powerful adaptogen for stress relief and vitality",
      price: 250,
      imageUrl: "https://images.unsplash.com/photo-1512237798647-84b57b22b517?w=600&h=400&fit=crop",
      categorySlug: "medicinal-plants",
      climate: "Subtropical, Arid",
      elevation: "0-2000m",
      season: "Year-round",
      sunlight: "Full Sun",
      waterNeed: "Low",
      soilType: "Sandy, well-draining",
      temperature: "20-35°C",
      matureHeight: "0.3-0.8m",
      spread: "0.3-0.5m",
      bloomTime: "Late Summer",
      difficulty: "Moderate",
      nutrients: "Low requirements",
      fertilizer: "Organic compost at planting",
      propagation: "Seeds",
      uses: "Medicine, Supplements, Tea",
      medicinalUses: "Stress relief, sleep aid, strength, immunity, anti-inflammatory, testosterone booster",
      edible: false,
      indoor: false,
      outdoor: true,
      fragrance: false,
      airPurifying: false,
      petSafe: false,
      stockCount: 30,
      featured: false,
    },
    {
      name: "Turmeric (Besar)",
      slug: "turmeric-besar",
      scientificName: "Curcuma longa",
      description: "The golden spice of Nepal! Turmeric is essential in Nepali cuisine, religious ceremonies, and traditional medicine. Its active compound curcumin has powerful anti-inflammatory and antioxidant properties. Easy to grow from rhizomes, and you can harvest your own fresh turmeric at home.",
      shortDesc: "Golden spice with powerful healing properties",
      price: 150,
      imageUrl: "https://images.unsplash.com/photo-1615485500704-8e990f9900f7?w=600&h=400&fit=crop",
      categorySlug: "medicinal-plants",
      climate: "Tropical, Subtropical",
      elevation: "0-1500m",
      season: "Monsoon planting, Winter harvest",
      sunlight: "Partial Shade",
      waterNeed: "Moderate to High",
      soilType: "Rich, moist, well-draining",
      temperature: "20-35°C",
      matureHeight: "0.5-1m",
      spread: "0.3-0.5m",
      bloomTime: "Monsoon",
      difficulty: "Easy",
      nutrients: "Potassium, Phosphorus",
      fertilizer: "Organic compost, well-rotted manure",
      propagation: "Rhizome division",
      uses: "Cooking, Medicine, Dye, Religious ceremonies",
      medicinalUses: "Anti-inflammatory, antioxidant, wound healing, digestive health, joint pain",
      edible: true,
      indoor: false,
      outdoor: true,
      fragrance: true,
      airPurifying: false,
      petSafe: true,
      stockCount: 40,
      featured: false,
    },
  ];

  console.log(`\n🌱 Seeding ${plants.length} plants...`);
  let createdCount = 0;
  let updatedCount = 0;

  for (let i = 0; i < plants.length; i++) {
    const p = plants[i];
    const categoryId = createdCategories[p.categorySlug];
    if (!categoryId) {
      console.warn(`  ⚠️ Category not found: ${p.categorySlug}, skipping ${p.name}`);
      continue;
    }

    const result = await prisma.plant.upsert({
      where: { slug: p.slug },
      update: {
        name: p.name,
        scientificName: p.scientificName,
        description: p.description,
        shortDesc: p.shortDesc,
        price: p.price,
        originalPrice: p.originalPrice,
        imageUrl: p.imageUrl,
        categoryId,
        climate: p.climate,
        elevation: p.elevation,
        season: p.season,
        sunlight: p.sunlight,
        waterNeed: p.waterNeed,
        soilType: p.soilType,
        soilPH: p.soilPH,
        temperature: p.temperature,
        humidity: p.humidity,
        matureHeight: p.matureHeight,
        spread: p.spread,
        bloomTime: p.bloomTime,
        difficulty: p.difficulty,
        nutrients: p.nutrients,
        fertilizer: p.fertilizer,
        pruning: p.pruning,
        propagation: p.propagation,
        companionPlants: p.companionPlants,
        uses: p.uses,
        medicinalUses: p.medicinalUses,
        edible: p.edible,
        indoor: p.indoor,
        outdoor: p.outdoor,
        fragrance: p.fragrance,
        airPurifying: p.airPurifying,
        petSafe: p.petSafe,
        stockCount: p.stockCount,
        featured: p.featured,
        displayOrder: i,
      },
      create: {
        name: p.name,
        slug: p.slug,
        scientificName: p.scientificName,
        description: p.description,
        shortDesc: p.shortDesc,
        price: p.price,
        originalPrice: p.originalPrice,
        imageUrl: p.imageUrl,
        categoryId,
        climate: p.climate,
        elevation: p.elevation,
        season: p.season,
        sunlight: p.sunlight,
        waterNeed: p.waterNeed,
        soilType: p.soilType,
        soilPH: p.soilPH,
        temperature: p.temperature,
        humidity: p.humidity,
        matureHeight: p.matureHeight,
        spread: p.spread,
        bloomTime: p.bloomTime,
        difficulty: p.difficulty,
        nutrients: p.nutrients,
        fertilizer: p.fertilizer,
        pruning: p.pruning,
        propagation: p.propagation,
        companionPlants: p.companionPlants,
        uses: p.uses,
        medicinalUses: p.medicinalUses,
        edible: p.edible,
        indoor: p.indoor,
        outdoor: p.outdoor,
        fragrance: p.fragrance,
        airPurifying: p.airPurifying,
        petSafe: p.petSafe,
        stockCount: p.stockCount,
        featured: p.featured,
        displayOrder: i,
      },
    });

    if (result.createdAt === result.updatedAt) {
      createdCount++;
    } else {
      updatedCount++;
    }
  }

  console.log(`  ✅ ${createdCount} plants created, ${updatedCount} plants updated`);

  // ===== SITE SETTINGS =====
  const defaults = [
    { key: "siteName", value: "GreenHaven Nursery" },
    { key: "heroBadge", value: "🌿 Nepal's Premier Online Nursery" },
    { key: "heroTitle", value: "Bring Nature\\nInto Your Home" },
    { key: "heroSubtitle", value: "Discover our handpicked collection of premium plants, expertly grown and delivered fresh to your doorstep across Nepal." },
    { key: "footerDescription", value: "GreenHaven Nursery — your trusted partner for premium plants and garden essentials in Nepal since 2020." },
    { key: "footerAddress", value: "Thamel, Kathmandu, Nepal" },
    { key: "footerPhone", value: "+977-9800000000" },
    { key: "footerEmail", value: "hello@greenhaven.com.np" },
    { key: "freeDeliveryThreshold", value: "2500" },
    { key: "deliveryFee", value: "150" },
    { key: "primaryColor", value: "oklch(0.32 0.12 155)" },
    { key: "goldColor", value: "oklch(0.72 0.13 80)" },
    { key: "socialMedia", value: JSON.stringify([
      { platform: "facebook", url: "https://facebook.com/greenhavennursery", enabled: true },
      { platform: "instagram", url: "https://instagram.com/greenhavennursery", enabled: true },
      { platform: "tiktok", url: "https://tiktok.com/@greenhavennursery", enabled: true },
      { platform: "youtube", url: "https://youtube.com/@greenhavennursery", enabled: true },
      { platform: "twitter", url: "https://twitter.com/greenhavennursery", enabled: true },
      { platform: "whatsapp", url: "https://wa.me/9779800000000", enabled: true },
    ]) },
    { key: "footerQuickLinks", value: JSON.stringify([
      { label: "Home", url: "/" },
      { label: "All Plants", url: "/#plants" },
      { label: "Flowering Plants", url: "/#flowering-plants" },
      { label: "Indoor Plants", url: "/#indoor-plants" },
      { label: "Herbs & Spices", url: "/#herbs-spices" },
      { label: "Fertilizers & Nutrients", url: "/#fertilizers-nutrients" },
      { label: "Pots & Equipment", url: "/#pots-equipment" },
      { label: "Contact Us", url: "/#contact" },
    ]) },
    { key: "footerCustomerService", value: JSON.stringify([
      { label: "My Orders", url: "/orders" },
      { label: "Shipping Policy", url: "/shipping" },
      { label: "Return Policy", url: "/returns" },
      { label: "Privacy Policy", url: "/privacy" },
      { label: "Terms & Conditions", url: "/terms" },
    ]) },
  ];

  for (const s of defaults) {
    await prisma.siteSetting.upsert({
      where: { key: s.key },
      update: {},
      create: s,
    });
  }
  console.log(`  📋 Site settings seeded (${defaults.length} settings)`);

  console.log("\n🎉 Database seeding complete!");
}

main()
  .catch(console.error)
  .finally(() => prisma.$disconnect());